using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.UI.Reactor.Localization.Generator;

// AI-HINT: Roslyn incremental source generator. Reads .resw files as AdditionalTexts,
//   emits a static Loc class with nested classes per .resw namespace, each containing
//   MessageKey constants. Also emits diagnostics for missing keys across locales.
//   Pipeline: AdditionalTexts → ReswParser → grouped by locale → diff default vs other → emit C#.

[Generator(LanguageNames.CSharp)]
public sealed class LocSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect .resw AdditionalFiles
        var reswFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".resw", StringComparison.OrdinalIgnoreCase));

        // Read the default locale property
        var defaultLocale = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.ReactorLocDefaultLocale", out var locale);
                return locale ?? "en-US";
            });

        // Read the missing key severity property
        var missingKeySeverity = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.ReactorLocMissingKeySeverity", out var severity);
                return severity ?? "Warning";
            });

        // Combine resw files into a collection
        var reswCollection = reswFiles.Collect();

        // Combine all inputs
        var combined = reswCollection
            .Combine(defaultLocale)
            .Combine(missingKeySeverity);

        context.RegisterSourceOutput(combined, static (spc, input) =>
        {
            var ((reswTexts, defaultLocale), missingKeySeverity) = input;
            Execute(spc, reswTexts, defaultLocale, missingKeySeverity);
        });
    }

    private static void Execute(
        SourceProductionContext context,
        ImmutableArray<AdditionalText> reswTexts,
        string defaultLocale,
        string missingKeySeverity)
    {
        if (reswTexts.IsDefaultOrEmpty) return;

        // Group files by locale folder and file name
        // Expected path pattern: .../Strings/{locale}/{FileName}.resw
        var filesByLocale = new Dictionary<string, Dictionary<string, List<ReswEntry>>>(StringComparer.OrdinalIgnoreCase);

        foreach (var text in reswTexts)
        {
            var content = text.GetText(context.CancellationToken)?.ToString();
            if (content == null) continue;

            var (locale, fileName) = ParseFilePath(text.Path);
            if (locale == null || fileName == null) continue;

            if (!filesByLocale.TryGetValue(locale, out var localeFiles))
            {
                localeFiles = new Dictionary<string, List<ReswEntry>>(StringComparer.OrdinalIgnoreCase);
                filesByLocale[locale] = localeFiles;
            }

            var entries = ReswParser.Parse(content);
            localeFiles[fileName] = entries;
        }

        // Find the default locale's files — these drive the generated code
        if (!filesByLocale.TryGetValue(defaultLocale, out var defaultFiles) || defaultFiles.Count == 0)
            return;

        // Determine layout type
        var fileNames = defaultFiles.Keys.ToList();
        var isFlat = ReswParser.IsFlatLayout(fileNames);

        // Emit Loc.g.cs
        var source = EmitLocClass(defaultFiles, isFlat);
        context.AddSource("Loc.g.cs", SourceText.From(source, Encoding.UTF8));

        // Emit missing key diagnostics
        EmitMissingKeyDiagnostics(context, filesByLocale, defaultLocale, defaultFiles, missingKeySeverity);
    }

    private static string EmitLocClass(
        Dictionary<string, List<ReswEntry>> defaultFiles,
        bool isFlat)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::System.CodeDom.Compiler;");
        sb.AppendLine("using Microsoft.UI.Reactor.Localization;");
        sb.AppendLine();

        if (isFlat)
        {
            // Flat layout: Loc.KeyName (no nesting)
            var entries = defaultFiles.Values.First();
            sb.AppendLine("[GeneratedCode(\"Reactor.Localization.Generator\", \"1.0.0\")]");
            sb.AppendLine("internal static class Loc");
            sb.AppendLine("{");
            EmitEntries(sb, "Resources", entries, "    ");
            sb.AppendLine("}");
        }
        else
        {
            // Namespaced layout: Loc.Namespace.KeyName
            sb.AppendLine("[GeneratedCode(\"Reactor.Localization.Generator\", \"1.0.0\")]");
            sb.AppendLine("internal static class Loc");
            sb.AppendLine("{");
            var classNameUsage = new HashSet<string>(StringComparer.Ordinal);
            foreach (var kvp in defaultFiles.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            {
                var ns = kvp.Key;
                var entries = kvp.Value;

                var classIdent = ResolveIdentifier(SanitizeIdentifier(ns), classNameUsage);
                sb.AppendLine($"    internal static class {classIdent}");
                sb.AppendLine("    {");
                EmitEntries(sb, ns, entries, "        ");
                sb.AppendLine("    }");
            }
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitEntries(StringBuilder sb, string ns, List<ReswEntry> entries, string indent)
    {
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entry in entries.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            EmitKeyField(sb, ns, entry, indent, used);
        }
    }

    private static void EmitKeyField(StringBuilder sb, string ns, ReswEntry entry, string indent, HashSet<string> usedIdentifiers)
    {
        // XML doc with the default-locale value for IntelliSense
        var escapedValue = entry.Value
            .Replace("\r\n", " ")
            .Replace("\n", " ")
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
        // SECURITY: SymbolDisplay.FormatLiteral produces a properly escaped C# string literal
        // (including surrounding quotes), so attacker-controlled .resw key/file names cannot
        // break out of the literal context and inject C# at build time.
        var nsLiteral = SymbolDisplay.FormatLiteral(ns, quote: true);
        var keyLiteral = SymbolDisplay.FormatLiteral(entry.Key, quote: true);
        var ident = ResolveIdentifier(SanitizeIdentifier(entry.Key), usedIdentifiers);
        sb.AppendLine($"{indent}/// <summary>{escapedValue}</summary>");
        sb.AppendLine($"{indent}public static readonly MessageKey {ident} = new({nsLiteral}, {keyLiteral});");
    }

    private static string ResolveIdentifier(string sanitized, HashSet<string> used)
    {
        // Disambiguate collisions (two .resw keys that sanitize to the same identifier)
        // by appending a numeric suffix. Comparison is ordinal so case differences alone
        // also collide, matching C# identifier rules in practice for our scope.
        if (used.Add(sanitized)) return sanitized;
        for (int i = 2; ; i++)
        {
            var candidate = sanitized + "_" + i.ToString(System.Globalization.CultureInfo.InvariantCulture);
            if (used.Add(candidate)) return candidate;
        }
    }

    private static void EmitMissingKeyDiagnostics(
        SourceProductionContext context,
        Dictionary<string, Dictionary<string, List<ReswEntry>>> filesByLocale,
        string defaultLocale,
        Dictionary<string, List<ReswEntry>> defaultFiles,
        string missingKeySeverity)
    {
        var severity = string.Equals(missingKeySeverity, "Error", StringComparison.OrdinalIgnoreCase)
            ? DiagnosticSeverity.Error
            : DiagnosticSeverity.Warning;

        var descriptor = new DiagnosticDescriptor(
            "REACTOR_LOC001",
            "Missing localization key",
            "Key '{0}.{1}' is present in {2} but missing in locale '{3}'",
            "Localization",
            severity,
            isEnabledByDefault: true);

        foreach (var localeKvp in filesByLocale)
        {
            var locale = localeKvp.Key;
            var localeFiles = localeKvp.Value;

            if (string.Equals(locale, defaultLocale, StringComparison.OrdinalIgnoreCase))
                continue;

            foreach (var defaultKvp in defaultFiles)
            {
                var fileName = defaultKvp.Key;
                var defaultEntries = defaultKvp.Value;

                if (!localeFiles.TryGetValue(fileName, out var localeEntries))
                {
                    // Entire file missing for this locale
                    foreach (var entry in defaultEntries)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            descriptor, Location.None, fileName, entry.Key, defaultLocale, locale));
                    }
                    continue;
                }

                var localeKeys = new HashSet<string>(localeEntries.Select(e => e.Key), StringComparer.Ordinal);
                foreach (var entry in defaultEntries)
                {
                    if (!localeKeys.Contains(entry.Key))
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            descriptor, Location.None, fileName, entry.Key, defaultLocale, locale));
                    }
                }
            }
        }
    }

    private static (string? locale, string? fileName) ParseFilePath(string path)
    {
        // Expected: .../Strings/{locale}/{FileName}.resw
        // or: .../{locale}/{FileName}.resw
        var normalized = path.Replace('\\', '/');
        var parts = normalized.Split('/');

        if (parts.Length < 2) return (null, null);

        var fileName = Path.GetFileNameWithoutExtension(parts[parts.Length - 1]);
        var locale = parts[parts.Length - 2];

        // Basic sanity: locale should look like "xx" or "xx-YY"
        if (locale.Length < 2 || locale.Length > 10) return (null, null);

        return (locale, fileName);
    }

    private static string SanitizeIdentifier(string name)
    {
        // Replace invalid C# identifier chars with underscore
        var sb = new StringBuilder(name.Length + 1);
        for (int i = 0; i < name.Length; i++)
        {
            var c = name[i];
            if (i == 0 && char.IsDigit(c))
                sb.Append('_');
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        if (sb.Length == 0) sb.Append('_');
        var ident = sb.ToString();
        // Reserved-keyword guard: prefix with `@` so `class`, `void`, etc. become valid identifiers.
        if (SyntaxFacts.GetKeywordKind(ident) != SyntaxKind.None
            || SyntaxFacts.GetContextualKeywordKind(ident) != SyntaxKind.None)
        {
            ident = "@" + ident;
        }
        return ident;
    }
}
