# Generates MainWindow.xaml with one explicit <TextBlock x:Bind .../> per
# cell, indexed off MainWindow.ViewModels. This is the "no wrapper" form of
# the x:Bind variant — the visual tree is exactly 4 900 raw TextBlocks (the
# same shape as StressPerf.Bound), and each binding is a compile-time hook
# generated by the WinUI XAML compiler against a known indexer position.
#
# Re-run this whenever StockDataSource.Columns / Rows change. The generated
# file is committed; the script is here so the regen path is auditable.

param(
  [string]$OutputPath = (Join-Path $PSScriptRoot 'MainWindow.xaml'),
  [int]$Rows = 70,
  [int]$Columns = 70,
  [int]$CellWidth = 64,
  [int]$CellHeight = 18
)

$total = $Rows * $Columns

$sb = [System.Text.StringBuilder]::new(2 * 1024 * 1024)
[void]$sb.AppendLine('<!--')
[void]$sb.AppendLine('    GENERATED — do not edit by hand.')
[void]$sb.AppendLine('    Regenerate via gen-mainwindow-xaml.ps1 in this directory.')
[void]$sb.AppendLine('-->')
[void]$sb.AppendLine('<Window')
[void]$sb.AppendLine('    x:Class="StressPerf.XBind.MainWindow"')
[void]$sb.AppendLine('    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"')
[void]$sb.AppendLine('    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"')
[void]$sb.AppendLine('    xmlns:local="using:StressPerf.XBind"')
[void]$sb.AppendLine('    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"')
[void]$sb.AppendLine('    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"')
[void]$sb.AppendLine('    mc:Ignorable="d">')
[void]$sb.AppendLine('    <Grid>')
[void]$sb.AppendLine('        <Grid.RowDefinitions>')
[void]$sb.AppendLine('            <RowDefinition Height="Auto"/>')
[void]$sb.AppendLine('            <RowDefinition Height="*"/>')
[void]$sb.AppendLine('        </Grid.RowDefinitions>')
[void]$sb.AppendLine('        <StackPanel Grid.Row="0" Orientation="Horizontal" Spacing="12" Padding="8">')
[void]$sb.AppendLine('            <Button x:Name="_toggleButton" Content="Start" Click="OnToggleClick"/>')
[void]$sb.AppendLine('            <TextBlock Text="Update %:" VerticalAlignment="Center"/>')
[void]$sb.AppendLine('            <Slider x:Name="_percentSlider" Minimum="0" Maximum="100" Width="200"/>')
[void]$sb.AppendLine('            <TextBlock x:Name="_fpsText" Text="FPS: --" VerticalAlignment="Center" Width="100"/>')
[void]$sb.AppendLine('            <TextBlock x:Name="_updateText" Text="Update: -- ms" VerticalAlignment="Center" Width="120"/>')
[void]$sb.AppendLine('            <TextBlock x:Name="_memText" Text="Mem: -- MB" VerticalAlignment="Center" Width="120"/>')
[void]$sb.AppendLine('        </StackPanel>')
[void]$sb.AppendLine('        <ScrollViewer Grid.Row="1" HorizontalScrollBarVisibility="Auto">')
[void]$sb.AppendLine('            <Grid>')
[void]$sb.AppendLine('                <Grid.RowDefinitions>')
for ($r = 0; $r -lt $Rows; $r++) {
  [void]$sb.AppendLine("                    <RowDefinition Height=`"$CellHeight`"/>")
}
[void]$sb.AppendLine('                </Grid.RowDefinitions>')
[void]$sb.AppendLine('                <Grid.ColumnDefinitions>')
for ($c = 0; $c -lt $Columns; $c++) {
  [void]$sb.AppendLine("                    <ColumnDefinition Width=`"$CellWidth`"/>")
}
[void]$sb.AppendLine('                </Grid.ColumnDefinitions>')

for ($i = 0; $i -lt $total; $i++) {
  # PowerShell's [int] uses banker's rounding, not truncation — [int](36/70)
  # rounds to 1, not 0. Use [Math]::Floor to get true integer division so
  # row indices are computed correctly.
  $r = [int][Math]::Floor($i / $Columns)
  $c = $i % $Columns
  [void]$sb.AppendLine("                <TextBlock Grid.Row=`"$r`" Grid.Column=`"$c`" FontSize=`"8`" Padding=`"2,1,2,1`" TextTrimming=`"CharacterEllipsis`" Text=`"{x:Bind ViewModels[$i].DisplayText, Mode=OneWay}`" Foreground=`"{x:Bind ViewModels[$i].PriceBrush, Mode=OneWay}`"/>")
}

[void]$sb.AppendLine('            </Grid>')
[void]$sb.AppendLine('        </ScrollViewer>')
[void]$sb.AppendLine('    </Grid>')
[void]$sb.AppendLine('</Window>')

[System.IO.File]::WriteAllText($OutputPath, $sb.ToString())
Write-Host "Wrote $OutputPath ($($total) cells, $([math]::Round($sb.Length/1KB)) KB)"
