using Microsoft.UI.Reactor.AppTests.Host.SelfTest.Fixtures;

namespace Microsoft.UI.Reactor.AppTests.Host.SelfTest;

/// <summary>
/// Maps fixture names to their self-test implementations (the ones with assertions).
/// </summary>
internal static class SelfTestFixtureRegistry
{
    public static readonly string[] AllFixtures =
    [
        "ErrorBoundary_CatchesRenderError",
        "ErrorBoundary_Recovery",
        "Reconciler_MountText",
        "Reconciler_UpdateText",
        "Reconciler_AddRemoveChildren",
        "Reconciler_ComponentRerender",
        "Reconciler_KeyedList",
        "Reconciler_GridDynamicChildCount",
        "Reconciler_AllLayoutsDynamicChildCount",
        "FlexLayout_RowDistribution",
        "FlexLayout_ColumnWrap",
        "Grid_RowColumnLayout",
        "GridVsFlex_StarSizing",
        "Flex_NestedRowInColumn",
        "Flex_NestedColumnInRow",
        "Flex_NestedDeep",
        "Flex_InsideGrid",
        "Flex_InsideBorder",
        "Flex_InsideVStack",
        "Flex_InsideScrollView",
        "Flex_ScrollViewInsideFlex",
        "Flex_ColumnGrow",
        "Flex_MixedGrowFixed",
        "Flex_WithGaps",
        "Flex_WithPadding",
        "Flex_CrossAxisTextHeight",
        "Flex_GridInsideFlex",
        "Flex_WithChildMargins",
        "Flex_JustifySpaceBetween",
        "Flex_LayoutCycleInGridStar",
        "Flex_LayoutCycleNestedDeep",
        "Flex_LayoutCycleAutoText",
        "Flex_LayoutCycleSizeMismatch",
        "Flex_WrapDepthMutation",
        "DynamicList_GrowShrink",
        "ConditionalRendering_Toggle",
        "Markdown_HeadingsAndFormatting",
        "Markdown_CodeBlockAndLinks",
        "Markdown_AllHeadingLevels",
        "Markdown_InlineFormatting",
        "Markdown_Links",
        "Markdown_BlockQuotes",
        "Markdown_UnorderedList",
        "Markdown_OrderedList",
        "Markdown_TaskList",
        "Markdown_TableWithAlignment",
        "Markdown_ThematicBreak",
        "Markdown_HtmlBlockPassthrough",
        "Markdown_FencedCodeWithLang",
        "Markdown_NestedList",
        "Markdown_ImageRendering",
        "Markdown_LineBreaks",
        "Markdown_EntityResolution",
        "Markdown_ComplexDocument",
        "Markdown_CustomOptionsCallbacks",
        "Markdown_CustomListCallbacks",
        "Markdown_CustomBlockQuoteHtml",
        "Markdown_CustomTableImage",
        "Markdown_Rerender",
        "Markdown_EmptyInput",
        "Markdown_InlineHtmlPassthrough",
        "D3_LineChart",
        "D3_BarChart",
        "D3_PieChart",
        "D3_AreaChart",
        "D3_TreeChart",
        "D3_ForceGraph",
        "D3_ChartCustomization",
        "D3_PieChartLabels",
        "D3Cov_Scatterplot",
        "D3Cov_Histogram",
        "D3Cov_DonutChart",
        "D3Cov_HorizontalBarChart",
        "D3Cov_Treemap",
        "D3Cov_Sunburst",
        "D3Cov_SankeyDiagram",
        "D3Cov_ChordDiagram",
        "D3Cov_StackedAreaChart",
        "D3Cov_D3Primitives",
        "D3Cov_MultiLineChart",
        "D3Cov_CirclePacking",
        "D3Cov_ScalesExercise",

        // Chart accessibility (Phase 1 + 2)
        "ChartA11y_PeerAttachment",
        "ChartA11y_GridProvider",
        "ChartA11y_PointValue",
        "ChartA11y_TableHeaders",
        "ChartA11y_PieChart",
        "ChartA11y_ForceGraph",
        "ChartA11y_DefaultPointLabels",
        "ChartA11y_CustomDataLabel",
        "ChartA11y_AutoSummary",
        "ChartA11y_AutoNameFromTitle",
        "ChartA11y_AutoNameFallback",
        // Chart accessibility (Phase 3 + 4)
        "ChartA11y_ForcedColorsPalette",
        "ChartA11y_DoubleEncoding",
        "ChartA11y_ColorOnlyWarning",
        "ChartA11y_Scanner_MissingTitle",
        "ChartA11y_Scanner_ColorOnly",
        "ChartA11y_Scanner_UnsafePalette",
        "ChartA11y_Scanner_Clean",
        // Chart accessibility (Phase 3 remaining + Phase 5)
        "ChartA11y_ReducedMotion",
        "ChartA11y_HitTargetExpansion",
        "ChartA11y_Scanner_InteractiveNoKeyboard",
        "ChartA11y_AlternateViewToggle",
        "ChartA11y_AlternateViewNoOp",
        // Chart accessibility (Phase 6 — keyboard navigation)
        "ChartA11y_KeyboardArrowNav",
        "ChartA11y_KeyboardHomeEnd",
        "ChartA11y_KeyboardSeriesSwitch",
        "ChartA11y_KeyboardInvoke",
        "ChartA11y_KeyboardEsc",
        // Chart accessibility (Phase 7 — viewport + live region)
        "ChartA11y_ViewportUIA",
        "ChartA11y_FocusContextSaveRestore",
        "ChartA11y_DecorationPruning",
        "ChartA11y_LiveRegionAnnounce",
        "ChartA11y_OnDemandAnnounce",
        "ChartA11y_FullIntegration",

        "MdHtml_HtmlGeneration",
        "MdHtml_HtmlInWebView2",
        "ListView_TypedRendering",
        "Navigation_TabSwitching",
        "Navigation_NavHostRendersInitial",
        "Navigation_NavHostContentSwap",
        "Navigation_NavHostGoBack",
        "Navigation_NavHostLifecycleOrder",
        "Navigation_NavHostNested",
        "Observable_UseObservable_Rerender",
        "Observable_UseObservable_ExternalMutation",
        "Observable_UseObservableProperty_FineGrained",
        "Observable_UseCollection_ListUpdates",
        "Observable_UseObservable_SourceSwap",
        // PropertyGrid
        "PropertyGrid_Reflection_MutableObject",
        "PropertyGrid_Reflection_Categorized",
        "PropertyGrid_Reflection_EnumEditor",
        "PropertyGrid_Nested_ImmutableRecord",
        "PropertyGrid_Immutable_Root",
        "PropertyGrid_Custom_Editor",
        "PropertyGrid_Target_Switching",
        "PropertyGrid_Category_ExpandCollapse",
        "PropertyGrid_DeepNesting_RecordInRecord",
        "PropertyGrid_INPC_ExternalMutation",
        // Localization
        "Localization_LocaleSwitching",
        // TypeRegistration mismatch regression
        "Reconciler_TypeMismatch_UpdateFallback",
        "Reconciler_TypeMismatch_UnmountSkip",
        // Control catalog — mount/unmount every control type
        "ControlCatalog_MountUnmountAll",
        // Reconciler stress tests — target uncovered branches
        "ReconcilerStress_KeyedSuffixMatch",
        "ReconcilerStress_KeyedMiddleRemoval",
        "ReconcilerStress_KeyedComplexReorder",
        "ReconcilerStress_KeyedInsertRemoveReorder",
        "ReconcilerStress_PositionalTypeMismatch",
        "ReconcilerStress_FuncElementRerender",
        "ReconcilerStress_ElementToNullTransition",
        "ReconcilerStress_ComponentUnmountCleanup",
        "ReconcilerStress_NestedContainerUnmount",
        "ReconcilerStress_KeyedLargeListStress",
        "ReconcilerStress_MultiCycleReconcile",
        "ReconcilerStress_KeyedPrefixTypeBreak",
        // Control update tests — exercise UpdateXxx dispatch + ApplyModifiers
        "ControlUpdate_TextProperty",
        "ControlUpdate_ButtonProperty",
        "ControlUpdate_InputControls",
        "ControlUpdate_DateTimePicker",
        "ControlUpdate_Containers",
        "ControlUpdate_Collections",
        "ControlUpdate_Navigation",
        "ControlUpdate_Modifiers",
        "ControlUpdate_PaddingModifiers",
        "ControlUpdate_Shapes",
        "ControlUpdate_StatusControls",
        "ControlUpdate_Grid",
        "ControlUpdate_ModifiedElementUnwrap",
        "ControlUpdate_HyperlinkButton",
        // Control update tests — wave 2 (remaining UpdateXxx + Mount paths)
        "ControlUpdate2_NavigationView",
        "ControlUpdate2_Image",
        "ControlUpdate2_AdditionalControls",
        "ControlUpdate2_TextBitmaskDiff",
        "ControlUpdate2_LegacyModifiedElement",
        "ControlUpdate2_ButtonVariants",
        "ControlUpdate2_ExpanderContent",
        "ControlUpdate2_VisibilityModifier",
        "ControlUpdate2_RichEditBox",
        "ControlUpdate2_AutoSuggestBox",
        // Modifier and event handler tests
        "ModifierEvent_EventHandlers",
        "ModifierEvent_Brushes",
        "ModifierEvent_Tooltip",
        "ModifierEvent_Automation",
        "ModifierEvent_ImplicitTransitions",
        "ModifierEvent_BorderModifiers",
        "ModifierEvent_OnMountAction",
        // Rare control mount + update tests
        "RareControl_ColorPicker",
        "RareControl_TeachingTip",
        "RareControl_GridView",
        "RareControl_PersonPicture",
        "RareControl_RelativePanel",
        "RareControl_CalendarView",
        "RareControl_RichTextBlock",
        "RareControl_PasswordBox",
        "RareControl_ComboBoxRadioButtons",
        // Component hook tests
        "ComponentHook_UseReducerFunctional",
        "ComponentHook_UseReducerRedux",
        "ComponentHook_UseMemoCallbackRef",
        "ComponentHook_UseEffectWithDeps",
        "ComponentHook_TypedProps",
        "ComponentHook_UseWindowSize",
        "ComponentHook_UseBreakpoint",
        "ComponentHook_MultipleComponents",
        // DSL and extension tests
        "DslExt_FluentModifierChain",
        "DslExt_TransitionExtensions",
        "DslExt_FactoryMethods",
        "DslExt_ShapeExtensions",
        "DslExt_GridBuilders",
        "DslExt_MenuDslMethods",
        "DslExt_AttachedProperties",
        "DslExt_ErrorBoundaryElement",
        "DslExt_GroupElement",
        "DslExt_BrushAndFontModifiers",
        // FlexPanel CSS behavior — Section A (CSS ↔ StackPanel agreement)
        "CssStack_BasicVerticalNoSpacing",
        "CssStack_VerticalWithSpacing",
        "CssStack_HorizontalWithSpacing",
        "CssStack_VerticalChildMarginsAndSpacing",
        "CssStack_EmptyPanel",
        "CssStack_SingleChild",
        "CssStack_CollapsedChildExcluded",
        "CssStack_HorizontalCrossStretch",
        // FlexPanel CSS behavior — Section B (CSS-only; FlexPanel follows CSS, not StackPanel)
        "CssDiverge_ExplicitHeightHonored",
        "CssDiverge_JustifyContentCenter",
        "CssDiverge_FlexGrowDistributesSpace",
        "CssDiverge_JustifyContentSpaceBetween",
        "CssDiverge_AlignSelfPerChild",
        "CssDiverge_FlexWrap",
        // Layout animation
        "LayoutAnimation_OffsetSetup",
        "LayoutAnimation_SpringSetup",
        "LayoutAnimation_SizeSetup",
        "ConnectedAnimation_MountUnmount",
        // Thread-safe hook stress tests — real WinUI rendering + background threads
        "ThreadSafe_RapidBackgroundSetState",
        "ThreadSafe_MultipleHooksConcurrent",
        "ThreadSafe_ReducerSerializationStress",
        "ThreadSafe_HighFrequencyLargeTree",
        "ThreadSafe_RenderCoalescing",
        // Animation system — Curve & Easing
        "Curve_RecordEquality",
        "Curve_PresetValues",
        "Curve_FactoryMethods",
        // Animation system — AnimationScope
        "AnimScope_SetRestore",
        "AnimScope_NestingBehavior",
        "AnimScope_NullCurveSuppresses",
        "AnimScope_WithAnimationIntegration",
        // Animation system — .Animate() modifier
        "Animate_ImplicitAnimationsCreated",
        "Animate_TargetedProperties",
        "Animate_MergesWithLayoutAnimation",
        // Animation system — InteractionStates
        "InterState_StateMachineTransitions",
        "InterState_PressedInheritsPointerOver",
        "InterState_ConfigImmutability",
        "InterState_NoLayoutProperties",
        "InterState_MountIntegration",
        // Animation system — Transitions
        "Transition_TypeHierarchy",
        "Transition_Asymmetric",
        "Transition_CurveResolutionPriority",
        "Transition_MountUnmountIntegration",
        // Animation system — WithAnimationAsync
        "AsyncAnim_TaskCompletes",
        "AsyncAnim_SequentialAwait",
        "AsyncAnim_ParallelWhenAll",
        // Animation system — Stagger
        "Stagger_DelayComputation",
        "Stagger_ComposesWithLayoutAnimation",
        "Stagger_ComposesWithEnterTransitions",
        // Animation system — Keyframe builder
        "Keyframe_BuilderProducesCorrectDef",
        "Keyframe_TriggerValueChange",
        "Keyframe_LoopFlag",
        // Animation system — Scroll-linked
        "ScrollAnim_ParallaxExpression",
        "ScrollAnim_FadeOutExpression",
        "ScrollAnim_FadeInExpression",
        "ScrollAnim_ScaleRangeExpression",
        "ScrollAnim_CustomExpression",
        // Animation combination tests — single features
        "AnimCombo_SpringAlone",
        "AnimCombo_EaseTargeted",
        "AnimCombo_LayoutAlone",
        "AnimCombo_FadeEnter",
        "AnimCombo_InteractionSetup",
        "AnimCombo_KeyframesOnMount",
        "AnimCombo_StaggerOnContainer",
        // Animation combination tests — pairs
        "AnimCombo_AnimatePlusLayout",
        "AnimCombo_AnimatePlusTransition",
        "AnimCombo_AnimatePlusInteraction",
        "AnimCombo_LayoutPlusTransition",
        "AnimCombo_TransitionCombined",
        "AnimCombo_AnimatePlusKeyframes",
        "AnimCombo_InteractionPlusTransition",
        // Animation combination tests — triple+
        "AnimCombo_Triple",
        "AnimCombo_FullContainerCombo",
        // Animation combination tests — update/rerender
        "AnimCombo_SurvivesUpdate",
        "AnimCombo_WithAnimationPlusAnimate",
        "AnimCombo_KeyframeTriggerUpdate",
        // Animation combination tests — removal
        "AnimCombo_AnimateRemoved",
        // Core coverage tests — targeting uncovered Reconciler/RenderContext paths
        "CoreCov_RichTextBlockParagraphUpdate",
        "CoreCov_RichTextBlockInlineReconciliation",
        "CoreCov_TemplatedGridViewMountUpdate",
        "CoreCov_TemplatedFlipViewMountUpdate",
        "CoreCov_LazyVStackMountUpdate",
        "CoreCov_ContentDialogMount",
        "CoreCov_CommandBarMountUpdate",
        "CoreCov_CommandHostMountUpdate",
        "CoreCov_MenuBarMountUpdate",
        "CoreCov_ThemeBindingApplication",
        "CoreCov_ResourceOverrideApplication",
        "CoreCov_AccessibilityModifiers",
        "CoreCov_UseCommandHook",
        "CoreCov_UseCommandTypedHook",
        "CoreCov_FlyoutMountUpdate",
        "CoreCov_SemanticZoomMountUpdate",
        "CoreCov_CompositorTransitions",
        "CoreCov_ThemeTransitions",
        "CoreCov_MemoComponentMountUpdate",
        "CoreCov_EventHandlerModifiers",
        "CoreCov_MenuFlyoutMount",
        "CoreCov_MediaPlayerMount",
        "CoreCov_LazyHStackMount",
        "CoreCov_UseSyncCommandPassthrough",
        "CoreCov_NavigationViewContentUpdate",
        "CoreCov_RelativePanelUpdate",
        "CoreCov_KeyframeCompositorAnimations",
        "CoreCov_SwipeControlMount",
        "CoreCov_ListBoxMount",
        "CoreCov_SelectorBarPipsPagerMount",
        "CoreCov_ThemeRefResolution",
        "CoreCov_PopupRefreshContainerMount",
        "CoreCov_AnnotatedScrollBarMount",
        "CoreCov_ContextProvideConsume",
        "CoreCov_ChildCollectionExercise",
        "CoreCov_AttachedFlyoutModifier",
        "CoreCov_TreeViewUpdateExercise",
        "CoreCov_AdvancedModifierCoverage",
        "CoreCov_ColorSchemeHook",
        "CoreCov_UseObservableDeep",
        "CoreCov_ErrorBoundaryUpdate",
        "CoreCov_ExpanderChildUpdateDeep",
        "CoreCov_CanvasPositionUpdate",
        // WinUI activation tests — migrated from unit tests that need FontFamily/SolidColorBrush
        "WinUI_FontFamilyStringOnButton",
        "WinUI_FontFamilyInstanceOnBorder",
        "WinUI_FontFamilyMergeOverwrites",
        "WinUI_TypographyModifiersMerge",
        "WinUI_BorderFluentBrush",
        "WinUI_ResourceBuilderStringBrush",
        "WinUI_ResourceBuilderFluentChaining",
        "WinUI_ResourceExtensionSetsOverrides",
        "WinUI_ResourceExtensionPreservesProps",
        "WinUI_ResourceExtensionMixedLiteralAndThemeRef",
        // Core coverage wave 2 — hooks, commands, controls
        "CoreCov2_UsePersistedHook",
        "CoreCov2_UseEffectCleanup",
        "CoreCov2_UseObservableTreeHook",
        "CoreCov2_StandardCommandExercise",
        "CoreCov2_CommandInteropExercise",
        "CoreCov2_InfoBarActionButton",
        "CoreCov2_CalendarPipsPagerUpdate",
        "CoreCov2_FrameAnimatedIconUpdate",
        "CoreCov2_ParallaxViewMount",
        "CoreCov2_XamlHostMount",
        "CoreCov2_ComponentTypedProps",
        "CoreCov2_ColorSchemeHookExercise",
        "CoreCov2_ContextScopeExercise",
        "CoreCov2_UseCommandAsyncExercise",
        "CoreCov2_UseCommandTypedAsyncExercise",
        "CoreCov2_ProplessComponentShouldUpdate",
        "CoreCov2_InfoBadgeMountUpdate",
        "CoreCov2_ListBoxUpdate",
        "CoreCov2_SelectorBarUpdate",
        // Hosting coverage — ReactorHostControl, ReactorHost paths, PageHelper
        "Hosting_HostControlMountComponent",
        "Hosting_HostControlMountFunc",
        "Hosting_HostControlFactory",
        "Hosting_HostControlRenderCallback",
        "Hosting_HostRenderStats",
        "Hosting_HostDispose",
        "Hosting_PageHelperExercise",
        "Hosting_XamlInteropRegister",
        // Navigation coverage — advanced handle ops, serialization, deep links, transitions
        "NavCov_HandleAdvancedOps",
        "NavCov_HandlePopTo",
        "NavCov_HandleSerialization",
        "NavCov_HandleNavigateOptions",
        "NavCov_DeepLinkMap",
        "NavCov_TransitionFactories",
        "NavCov_HandleEvents",
        "NavCov_DestinationGuard",
        "NavCov_DeepLinkQueryString",
        "NavCov_DeepLinkOptionalParam",
        "NavCov_DeepLinkWildcard",
        "NavCov_DiagnosticsEvents",
        "NavCov_SlideDistance",
        // Validation coverage — context, validators, form fields, rules
        "ValCov_ValidationContext",
        "ValCov_BuiltInValidators",
        "ValCov_ValidateExtensions",
        "ValCov_FormFieldRendering",
        "ValCov_ValidationRule",
        "ValCov_FormFieldHelpers",
        // Controls coverage — MaskEngine, InputFormatter, AutoSuggest
        "ControlsCov_MaskEngineBasic",
        "ControlsCov_MaskEngineNavigation",
        "ControlsCov_MaskEngineTokenTypes",
        "ControlsCov_InputFormattersBasic",
        "ControlsCov_InputFormattersCasing",
        "ControlsCov_InputFormattersFiltering",
        "ControlsCov_FormatterPipeline",
        "ControlsCov_AutoSuggestElement",
        "ControlsCov_SearchManager",
        // Echo-suppression — programmatic Update* writes must not re-enter onChange
        "EchoSuppress_ColorPicker",
        "EchoSuppress_NumberBox",
        "EchoSuppress_NumberBoxMinMaxCoercion",
        "EchoSuppress_ToggleSwitch",
        "EchoSuppress_CheckBox",
        "EchoSuppress_Slider",
        "EchoSuppress_SliderMinMaxCoercion",
        "EchoSuppress_RatingControl",
        "EchoSuppress_DatePicker",
        "EchoSuppress_CalendarDatePicker",
        "EchoSuppress_TimePicker",
        "EchoSuppress_PasswordBox",
        "EchoSuppress_TextField",
        "EchoSuppress_ToggleSplitButton",
        // Control identity preservation under unrelated sibling re-render.
        // Regression coverage for the "Update falls through to Mount" bug
        // fixed in #76 — verifies the 14 controls' WinUI instances survive.
        "IdentityPreserve_ComboBox",
        "IdentityPreserve_ComboBoxElements",
        "IdentityPreserve_RadioButtons",
        "IdentityPreserve_TabView",
        "IdentityPreserve_Pivot",
        "IdentityPreserve_ListBox",
        "IdentityPreserve_SelectorBar",
        "IdentityPreserve_SplitView",
        // Hooks coverage — FocusManager, UseFocus
        "HooksCov_FocusManagerRegistration",
        "HooksCov_FocusManagerNavigation",
        "HooksCov_FocusManagerWithControls",
        "HooksCov_UseFocusHookIntegration",
        // DataGrid inline editing
        "DataGrid_EditLifecycle",
        "DataGrid_EditCommitCycle",
        "DataGrid_EditCellColumnPlacement",
        "DataGrid_RapidSelection",
        "DataGrid_ExternalStateUpdate",
        "DataGrid_CellTypeFlipPreservesTrailingCells",
        // DataGrid incremental paging
        "DataGrid_IncrementalLoadVerification",
        "DataGrid_SmallDatasetFullyLoaded",
        // DataGrid scroll behavior and performance
        "DataGrid_ScrollPopulatesData",
        "DataGrid_ScrollBackPopulatesData",
        "DataGrid_ScrollPerfRelative",
        // DataGrid parity — hook-based paging path (Phase 3)
        "DataGrid_HookPagingMountAndLoad",
        "DataGrid_HookPagingScrollPopulates",
        "DataGrid_HookPagingScrollBack",
        "DataGrid_HookPagingSmallDataset",
        "DataGrid_HookPagingEditLifecycle",
        "AsyncResource.Framerate.DataGridScroll",
        // UseResource integration (real dispatcher)
        "AsyncResource.BasicResolve",
        "AsyncResource.SyncCompleteNoFlash",
        "AsyncResource.StaleWhileRevalidate",
        "AsyncResource.DepsChangeCancel",
        "AsyncResource.UnmountDuringFetch",
        "AsyncResource.FocusRevalidate",
        // Pending bubble-up scope
        "AsyncResource.PendingBubbleUp",
        "AsyncResource.PendingWithOverride",
        // UseMutation under real dispatcher
        "AsyncResource.MutationOptimistic",
        "AsyncResource.MutationRollback",
        "AsyncResource.MutationInvalidates",
        // UseInfiniteResource under real dispatcher
        "AsyncResource.InfiniteBasic",
        "AsyncResource.InfinitePlaceholder",
        "AsyncResource.InfiniteRefresh",
        "AsyncResource.InfiniteDepsChange",
        // Framerate canaries — "works in isolation, breaks at 60Hz" regression net
        "AsyncResource.Framerate.DepsThrashing",
        "AsyncResource.Framerate.RenderShortCircuit",
        "AsyncResource.Framerate.CacheChurn",
        "AsyncResource.Framerate.FastRemount",
        "AsyncResource.Framerate.DispatcherPressure",
        "AsyncResource.Framerate.DataGridEditMutation",
        // Infinite-resource framerate canaries
        "AsyncResource.Framerate.ScrollFlood",
        "AsyncResource.Framerate.RapidEnsureRange",
        "AsyncResource.Framerate.RefreshMidScroll",
        "AsyncResource.Framerate.LruChurn",
        "AsyncResource.Framerate.ParallelPages",
        // Pending scope framerate canary
        "AsyncResource.Framerate.PendingChurn",
        // AI agent devtools — MCP server exercised in-process with real WinUI
        "Devtools_VersionTool",
        "Devtools_ComponentsTool",
        "Devtools_WindowsTool",
        "Devtools_TreeSummary",
        "Devtools_TreeFullView",
        "Devtools_TreeSelectorScope",
        "Devtools_ClickInvokesButton",
        "Devtools_TypeSetsTextBox",
        "Devtools_FocusElement",
        "Devtools_WaitForTextChange",
        "Devtools_WaitForTimeout",
        "Devtools_ToggleFlipsCheckBox",
        "Devtools_InvokeDirectPattern",
        "Devtools_StateReadsHooks",
        "Devtools_ScreenshotReturnsPng",
        "Devtools_SelectListItem",
        "Devtools_ScrollByAndInto",
        "Devtools_LoggerWritesOneLinePerCall",
        "Devtools_UnknownSelectorStructuredError",
        "Devtools_NameSelectorMatchesButtonContent",
        "Devtools_TreeIdsUniqueAcrossSiblingsWithDifferentParents",
        "Devtools_FireRejectsLifecycleMethods",
        "Devtools_FireInvokesNamedHandler",
        "Devtools_WaitForTimeoutLoggedAsErr",
        "Devtools_InitializeHandshake",
        "Devtools_SwitchComponentInvalidatesIds",
        // Coverage boost — targeting remaining gaps to reach 85%
        "CovBoost_ComponentHookWrappers",
        "CovBoost_ThemeTokenResolution",
        "CovBoost_ElementPoolExercise",
        "CovBoost_FlexPanelAttachedProps",
        "CovBoost_FlexPanelContainerProps",
        "CovBoost_UseSystemBackButton",
        "CovBoost_UseHighContrastScheme",
        "CovBoost_UseAnnounce",
        "CovBoost_ElementPoolLifecycle",
        "CovBoost_ThemeRefExplicitResolution",
        "CovBoost_ComponentUseMutation",
        "CovBoost_ComponentUseResource",
        "CovBoost_FlexPanelUnloadCleanup",
        "CovBoost_ElementPoolDetach",
        "CovBoost_UseWindowSizeBreakpoint",
        // Coverage boost wave 2 — Reconciler, validation, animation, semantic
        "CovBoost2_SemanticElement",
        "CovBoost2_ValidationVisualizerStyles",
        "CovBoost2_TitleBarMountUpdate",
        "CovBoost2_ReconcileChildPaths",
        "CovBoost2_RichToolTipUpdate",
        "CovBoost2_FlexChildPropChange",
        "CovBoost2_ResourceOverrideCleanup",
        "CovBoost2_NavigationViewExercise",
        "CovBoost2_TemplatedListExercise",
        "CovBoost2_CompositionTransition",
        "CovBoost2_AnimationCurveExercise",
        "CovBoost2_RichTextRebuild",
        "CovBoost2_ElementPoolInteractiveReset",
        "CovBoost2_DataGridSearchSort",
        "CovBoost2_FocusTrapExercise",

        // Input modifiers — spec 027 Tier 1
        "PointerMod_DoubleTappedAutoEnables",
        "PointerMod_RightTappedAutoEnables",
        "PointerMod_HoldingAutoEnables",
        "PointerMod_ShapePointerHandlerAutoFillsTransparent",
        "PointerMod_ShapeWithExplicitFillNotOverwritten",
        "PointerMod_GotLostFocusFires",
        "PointerMod_AutoEnableClearsOnDetach",

        // Trampoline dispatch — spec 027 Tier 2
        "Trampoline_LatestHandlerWinsAfterRerender",
        "Trampoline_HandlerRemovedBecomesNoOp",
        "Trampoline_ReRenderSameControlUnderlyingRefStable",

        // Gesture recognizers — spec 027 Tier 3
        "Gesture_OnPanSetsManipulationMode",
        "Gesture_OnPanWithInertiaAddsInertiaFlag",
        "Gesture_OnPinchSetsScaleFlag",
        "Gesture_OnRotateSetsRotateFlag",
        "Gesture_PanAndPinchCombine",

        // LongPress + focus — spec 027 Tier 3 Part 2 / Tier 5 (Phase 4)
        "Gesture_OnLongPressAutoEnablesHolding",
        "Gesture_OnLongPressMouseEmulationOptIn",
        "Focus_AccessKeySetsProperty",
        "Focus_IsTabStopFalseSkipsTabNav",
        "Focus_XYFocusKeyboardNavigationSets",
        "Focus_RefModifierPopulatesOnMount",
        "Focus_FocusManagerFocusReturnsTrueWhenMounted",

        // Commanding coverage — spec 027 Tier 4 (Phase 5)
        "Commanding_SplitButtonCommandInvokesExecute",
        "Commanding_HyperlinkButtonCommandInvokesExecute",
        "Commanding_ToggleButtonCommandFiresOnToggle",
        "Commanding_RepeatButtonCommandInvokesExecute",
        "Commanding_DisabledCommandDisablesControl",

        // Drag-and-drop — spec 027 Tier 6 (Phase 6a)
        "DragDrop_OnDragStartAutoSetsCanDrag",
        "DragDrop_OnDropAutoSetsAllowDrop",
        "DragDrop_RawOnDropAutoSetsAllowDrop",
        "DragDrop_DragEnterHandlerAutoSetsAllowDrop",
        "DragDrop_SourceAndTargetOnSameElement",
        "DragDrop_DraggableWhenWithoutPayloadStillSetsCanDrag",

        // Devtools UX — spec 028
        "DevtoolsUx_MenuHiddenWhenDisabled",
        "DevtoolsUx_MenuVisibleWhenEnabled",
        "DevtoolsUx_ObservableToggleRerendersSubscribers",

        // Selection-event wiring (Tier 2 gap closure)
        "SelectionEvt_ComboBox",
        "SelectionEvt_RadioButtons",
        "SelectionEvt_ListView",
        "SelectionEvt_GridView",
        "SelectionEvt_FlipView",
        "SelectionEvt_TabView",
        "SelectionEvt_Pivot",
        "SelectionEvt_NavigationView",

        // Value-change / toggle event wiring (Tier 2 gap closure)
        "ValueEvt_CheckBox",
        "ValueEvt_RadioButton",
        "ValueEvt_ToggleSwitch",
        "ValueEvt_Slider",
        "ValueEvt_NumberBox",
        "ValueEvt_RatingControl",
        "ValueEvt_PasswordBox",
        "ValueEvt_ColorPicker",

        // Specialized editors — HitTable-style typed editors
        "Editors_CheckBoxMounts",
        "Editors_ToggleMounts",
        "Editors_NumberMounts",
        "Editors_DateMounts",
        "Editors_ColorMounts",
        "Editors_ColorCompactMounts",
        "Renderers_HyperlinkMounts",
        "Renderers_ColorSwatchMounts",

        // Reconcile-highlight overlay
        "ReconcileHighlight_MountCapturesElements",
        "ReconcileHighlight_UpdateCapturesModified",
        "ReconcileHighlight_NoCaptureWhenFlagOff",
        "ReconcileHighlight_ContainerNotModifiedWhenOnlyChildrenChange",
        "ReconcileHighlight_UpdatePathNotRemount",
        "ReconcileHighlight_MenuFlyoutUpdatesInPlace",
    ];

    public static SelfTestFixtureBase? Create(string name, Harness harness) => name switch
    {
        "ErrorBoundary_CatchesRenderError" => new ErrorBoundaryFixtures.CatchesRenderError(harness),
        "ErrorBoundary_Recovery" => new ErrorBoundaryFixtures.Recovery(harness),
        "Reconciler_MountText" => new ReconcilerFixtures.MountText(harness),
        "Reconciler_UpdateText" => new ReconcilerFixtures.UpdateText(harness),
        "Reconciler_AddRemoveChildren" => new ReconcilerFixtures.AddRemoveChildren(harness),
        "Reconciler_ComponentRerender" => new ReconcilerFixtures.ComponentRerender(harness),
        "Reconciler_KeyedList" => new ReconcilerFixtures.KeyedList(harness),
        "Reconciler_GridDynamicChildCount" => new ReconcilerFixtures.GridDynamicChildCount(harness),
        "Reconciler_AllLayoutsDynamicChildCount" => new ReconcilerFixtures.AllLayoutsDynamicChildCount(harness),
        "FlexLayout_RowDistribution" => new LayoutFixtures.FlexRowDistribution(harness),
        "FlexLayout_ColumnWrap" => new LayoutFixtures.FlexColumnWrap(harness),
        "Grid_RowColumnLayout" => new LayoutFixtures.GridRowColumn(harness),
        "GridVsFlex_StarSizing" => new LayoutFixtures.GridVsFlexStarSizing(harness),
        "Flex_NestedRowInColumn" => new FlexLayoutFixtures.FlexNestedRowInColumn(harness),
        "Flex_NestedColumnInRow" => new FlexLayoutFixtures.FlexNestedColumnInRow(harness),
        "Flex_NestedDeep" => new FlexLayoutFixtures.FlexNestedDeep(harness),
        "Flex_InsideGrid" => new FlexLayoutFixtures.FlexInsideGrid(harness),
        "Flex_InsideBorder" => new FlexLayoutFixtures.FlexInsideBorder(harness),
        "Flex_InsideVStack" => new FlexLayoutFixtures.FlexInsideVStack(harness),
        "Flex_InsideScrollView" => new FlexLayoutFixtures.FlexInsideScrollView(harness),
        "Flex_ScrollViewInsideFlex" => new FlexLayoutFixtures.ScrollViewInsideFlex(harness),
        "Flex_ColumnGrow" => new FlexLayoutFixtures.FlexColumnGrow(harness),
        "Flex_MixedGrowFixed" => new FlexLayoutFixtures.FlexMixedGrowFixed(harness),
        "Flex_WithGaps" => new FlexLayoutFixtures.FlexWithGaps(harness),
        "Flex_WithPadding" => new FlexLayoutFixtures.FlexWithPadding(harness),
        "Flex_CrossAxisTextHeight" => new FlexLayoutFixtures.FlexCrossAxisTextHeight(harness),
        "Flex_GridInsideFlex" => new FlexLayoutFixtures.GridInsideFlex(harness),
        "Flex_WithChildMargins" => new FlexLayoutFixtures.FlexWithChildMargins(harness),
        "Flex_JustifySpaceBetween" => new FlexLayoutFixtures.FlexJustifySpaceBetween(harness),
        "Flex_LayoutCycleInGridStar" => new FlexLayoutFixtures.FlexLayoutCycleInGridStar(harness),
        "Flex_LayoutCycleNestedDeep" => new FlexLayoutFixtures.FlexLayoutCycleNestedDeep(harness),
        "Flex_LayoutCycleAutoText" => new FlexLayoutFixtures.FlexLayoutCycleAutoText(harness),
        "Flex_LayoutCycleSizeMismatch" => new FlexLayoutFixtures.FlexLayoutCycleSizeMismatch(harness),
        "Flex_WrapDepthMutation" => new FlexLayoutFixtures.FlexWrapDepthMutation(harness),
        "DynamicList_GrowShrink" => new DynamicFixtures.ListGrowShrink(harness),
        "ConditionalRendering_Toggle" => new DynamicFixtures.ConditionalToggle(harness),
        "Markdown_HeadingsAndFormatting" => new MarkdownFixtures.HeadingsAndFormatting(harness),
        "Markdown_CodeBlockAndLinks" => new MarkdownFixtures.CodeBlockAndLinks(harness),
        "Markdown_AllHeadingLevels" => new MarkdownFixtures.AllHeadingLevels(harness),
        "Markdown_InlineFormatting" => new MarkdownFixtures.InlineFormatting(harness),
        "Markdown_Links" => new MarkdownFixtures.Links(harness),
        "Markdown_BlockQuotes" => new MarkdownFixtures.BlockQuotes(harness),
        "Markdown_UnorderedList" => new MarkdownFixtures.UnorderedList(harness),
        "Markdown_OrderedList" => new MarkdownFixtures.OrderedList(harness),
        "Markdown_TaskList" => new MarkdownFixtures.TaskList(harness),
        "Markdown_TableWithAlignment" => new MarkdownFixtures.TableWithAlignment(harness),
        "Markdown_ThematicBreak" => new MarkdownFixtures.ThematicBreak(harness),
        "Markdown_HtmlBlockPassthrough" => new MarkdownFixtures.HtmlBlockPassthrough(harness),
        "Markdown_FencedCodeWithLang" => new MarkdownFixtures.FencedCodeWithLang(harness),
        "Markdown_NestedList" => new MarkdownFixtures.NestedList(harness),
        "Markdown_ImageRendering" => new MarkdownFixtures.ImageRendering(harness),
        "Markdown_LineBreaks" => new MarkdownFixtures.LineBreaks(harness),
        "Markdown_EntityResolution" => new MarkdownFixtures.EntityResolution(harness),
        "Markdown_ComplexDocument" => new MarkdownFixtures.ComplexDocument(harness),
        "Markdown_CustomOptionsCallbacks" => new MarkdownFixtures.CustomOptionsCallbacks(harness),
        "Markdown_CustomListCallbacks" => new MarkdownFixtures.CustomListCallbacks(harness),
        "Markdown_CustomBlockQuoteHtml" => new MarkdownFixtures.CustomBlockQuoteHtml(harness),
        "Markdown_CustomTableImage" => new MarkdownFixtures.CustomTableImage(harness),
        "Markdown_Rerender" => new MarkdownFixtures.MarkdownRerender(harness),
        "Markdown_EmptyInput" => new MarkdownFixtures.EmptyInput(harness),
        "Markdown_InlineHtmlPassthrough" => new MarkdownFixtures.InlineHtmlPassthrough(harness),
        "D3_LineChart" => new D3Fixtures.LineChart(harness),
        "D3_BarChart" => new D3Fixtures.BarChart(harness),
        "D3_PieChart" => new D3Fixtures.PieChart(harness),
        "D3_AreaChart" => new D3Fixtures.AreaChart(harness),
        "D3_TreeChart" => new D3Fixtures.TreeChart(harness),
        "D3_ForceGraph" => new D3Fixtures.ForceGraph(harness),
        "D3_ChartCustomization" => new D3Fixtures.ChartCustomization(harness),
        "D3_PieChartLabels" => new D3Fixtures.PieChartLabels(harness),
        "D3Cov_Scatterplot" => new D3ChartCoverageFixtures.Scatterplot(harness),
        "D3Cov_Histogram" => new D3ChartCoverageFixtures.Histogram(harness),
        "D3Cov_DonutChart" => new D3ChartCoverageFixtures.DonutChart(harness),
        "D3Cov_HorizontalBarChart" => new D3ChartCoverageFixtures.HorizontalBarChart(harness),
        "D3Cov_Treemap" => new D3ChartCoverageFixtures.Treemap(harness),
        "D3Cov_Sunburst" => new D3ChartCoverageFixtures.Sunburst(harness),
        "D3Cov_SankeyDiagram" => new D3ChartCoverageFixtures.SankeyDiagram(harness),
        "D3Cov_ChordDiagram" => new D3ChartCoverageFixtures.ChordDiagram(harness),
        "D3Cov_StackedAreaChart" => new D3ChartCoverageFixtures.StackedAreaChart(harness),
        "D3Cov_D3Primitives" => new D3ChartCoverageFixtures.D3Primitives(harness),
        "D3Cov_MultiLineChart" => new D3ChartCoverageFixtures.MultiLineChart(harness),
        "D3Cov_CirclePacking" => new D3ChartCoverageFixtures.CirclePacking(harness),
        "D3Cov_ScalesExercise" => new D3ChartCoverageFixtures.ScalesExercise(harness),

        // Chart accessibility (Phase 1 + 2)
        "ChartA11y_PeerAttachment" => new ChartAccessibilityFixtures.PeerAttachment(harness),
        "ChartA11y_GridProvider" => new ChartAccessibilityFixtures.GridProvider(harness),
        "ChartA11y_PointValue" => new ChartAccessibilityFixtures.PointValue(harness),
        "ChartA11y_TableHeaders" => new ChartAccessibilityFixtures.TableHeaders(harness),
        "ChartA11y_PieChart" => new ChartAccessibilityFixtures.PieChart(harness),
        "ChartA11y_ForceGraph" => new ChartAccessibilityFixtures.ForceGraph(harness),
        "ChartA11y_DefaultPointLabels" => new ChartAccessibilityFixtures.DefaultPointLabels(harness),
        "ChartA11y_CustomDataLabel" => new ChartAccessibilityFixtures.CustomDataLabel(harness),
        "ChartA11y_AutoSummary" => new ChartAccessibilityFixtures.AutoSummary(harness),
        "ChartA11y_AutoNameFromTitle" => new ChartAccessibilityFixtures.AutoNameFromTitle(harness),
        "ChartA11y_AutoNameFallback" => new ChartAccessibilityFixtures.AutoNameFallback(harness),
        // Chart accessibility (Phase 3 + 4)
        "ChartA11y_ForcedColorsPalette" => new ChartAccessibilityFixtures.ForcedColorsPalette(harness),
        "ChartA11y_DoubleEncoding" => new ChartAccessibilityFixtures.DoubleEncoding(harness),
        "ChartA11y_ColorOnlyWarning" => new ChartAccessibilityFixtures.ColorOnlyWarning(harness),
        "ChartA11y_Scanner_MissingTitle" => new ChartAccessibilityFixtures.ScannerMissingTitle(harness),
        "ChartA11y_Scanner_ColorOnly" => new ChartAccessibilityFixtures.ScannerColorOnly(harness),
        "ChartA11y_Scanner_UnsafePalette" => new ChartAccessibilityFixtures.ScannerUnsafePalette(harness),
        "ChartA11y_Scanner_Clean" => new ChartAccessibilityFixtures.ScannerClean(harness),
        // Chart accessibility (Phase 3 remaining + Phase 5)
        "ChartA11y_ReducedMotion" => new ChartAccessibilityFixtures.ReducedMotion(harness),
        "ChartA11y_HitTargetExpansion" => new ChartAccessibilityFixtures.HitTargetExpansion(harness),
        "ChartA11y_Scanner_InteractiveNoKeyboard" => new ChartAccessibilityFixtures.ScannerInteractiveNoKeyboard(harness),
        "ChartA11y_AlternateViewToggle" => new ChartAccessibilityFixtures.AlternateViewToggle(harness),
        "ChartA11y_AlternateViewNoOp" => new ChartAccessibilityFixtures.AlternateViewNoOp(harness),
        // Chart accessibility (Phase 6 — keyboard navigation)
        "ChartA11y_KeyboardArrowNav" => new ChartAccessibilityFixtures.KeyboardArrowNav(harness),
        "ChartA11y_KeyboardHomeEnd" => new ChartAccessibilityFixtures.KeyboardHomeEnd(harness),
        "ChartA11y_KeyboardSeriesSwitch" => new ChartAccessibilityFixtures.KeyboardSeriesSwitch(harness),
        "ChartA11y_KeyboardInvoke" => new ChartAccessibilityFixtures.KeyboardInvoke(harness),
        "ChartA11y_KeyboardEsc" => new ChartAccessibilityFixtures.KeyboardEsc(harness),
        // Chart accessibility (Phase 7 — viewport + live region)
        "ChartA11y_ViewportUIA" => new ChartAccessibilityFixtures.ViewportUIA(harness),
        "ChartA11y_FocusContextSaveRestore" => new ChartAccessibilityFixtures.FocusContextSaveRestore(harness),
        "ChartA11y_DecorationPruning" => new ChartAccessibilityFixtures.DecorationPruning(harness),
        "ChartA11y_LiveRegionAnnounce" => new ChartAccessibilityFixtures.LiveRegionAnnounce(harness),
        "ChartA11y_OnDemandAnnounce" => new ChartAccessibilityFixtures.OnDemandAnnounce(harness),
        "ChartA11y_FullIntegration" => new ChartAccessibilityFixtures.FullIntegration(harness),

        "MdHtml_HtmlGeneration" => new MarkdownHtmlFixtures.HtmlGeneration(harness),
        "MdHtml_HtmlInWebView2" => new MarkdownHtmlFixtures.HtmlInWebView2(harness),
        "ListView_TypedRendering" => new CollectionFixtures.ListViewTyped(harness),
        "Navigation_TabSwitching" => new NavigationFixtures.TabSwitching(harness),
        "Navigation_NavHostRendersInitial" => new NavigationFixtures.NavHostRendersInitial(harness),
        "Navigation_NavHostContentSwap" => new NavigationFixtures.NavHostContentSwap(harness),
        "Navigation_NavHostGoBack" => new NavigationFixtures.NavHostGoBack(harness),
        "Navigation_NavHostLifecycleOrder" => new NavigationFixtures.NavHostLifecycleOrder(harness),
        "Navigation_NavHostNested" => new NavigationFixtures.NavHostNested(harness),
        "Observable_UseObservable_Rerender" => new ObservableFixtures.UseObservable_Rerender(harness),
        "Observable_UseObservable_ExternalMutation" => new ObservableFixtures.UseObservable_ExternalMutation(harness),
        "Observable_UseObservableProperty_FineGrained" => new ObservableFixtures.UseObservableProperty_FineGrained(harness),
        "Observable_UseCollection_ListUpdates" => new ObservableFixtures.UseCollection_ListUpdates(harness),
        "Observable_UseObservable_SourceSwap" => new ObservableFixtures.UseObservable_SourceSwap(harness),
        // PropertyGrid
        "PropertyGrid_Reflection_MutableObject" => new PropertyGridFixtures.Reflection_MutableObject(harness),
        "PropertyGrid_Reflection_Categorized" => new PropertyGridFixtures.Reflection_Categorized(harness),
        "PropertyGrid_Reflection_EnumEditor" => new PropertyGridFixtures.Reflection_EnumEditor(harness),
        "PropertyGrid_Nested_ImmutableRecord" => new PropertyGridFixtures.Nested_ImmutableRecord(harness),
        "PropertyGrid_Immutable_Root" => new PropertyGridFixtures.Immutable_Root(harness),
        "PropertyGrid_Custom_Editor" => new PropertyGridFixtures.Custom_Editor(harness),
        "PropertyGrid_Target_Switching" => new PropertyGridFixtures.Target_Switching(harness),
        "PropertyGrid_Category_ExpandCollapse" => new PropertyGridFixtures.Category_ExpandCollapse(harness),
        "PropertyGrid_DeepNesting_RecordInRecord" => new PropertyGridFixtures.DeepNesting_RecordInRecord(harness),
        "PropertyGrid_INPC_ExternalMutation" => new PropertyGridFixtures.INPC_ExternalMutation(harness),
        // Localization
        "Localization_LocaleSwitching" => new LocalizationFixtures.LocaleSwitching(harness),
        // TypeRegistration mismatch regression
        "Reconciler_TypeMismatch_UpdateFallback" => new TypeRegistrationMismatchFixtures.UpdateControlTypeMismatch(harness),
        "Reconciler_TypeMismatch_UnmountSkip" => new TypeRegistrationMismatchFixtures.UnmountControlTypeMismatch(harness),
        // Control catalog
        "ControlCatalog_MountUnmountAll" => new ControlCatalogFixtures.MountUnmountAllControls(harness),
        // Reconciler stress tests
        "ReconcilerStress_KeyedSuffixMatch" => new ReconcilerStressFixtures.KeyedSuffixMatch(harness),
        "ReconcilerStress_KeyedMiddleRemoval" => new ReconcilerStressFixtures.KeyedMiddleRemoval(harness),
        "ReconcilerStress_KeyedComplexReorder" => new ReconcilerStressFixtures.KeyedComplexReorder(harness),
        "ReconcilerStress_KeyedInsertRemoveReorder" => new ReconcilerStressFixtures.KeyedInsertRemoveReorder(harness),
        "ReconcilerStress_PositionalTypeMismatch" => new ReconcilerStressFixtures.PositionalTypeMismatch(harness),
        "ReconcilerStress_FuncElementRerender" => new ReconcilerStressFixtures.FuncElementRerender(harness),
        "ReconcilerStress_ElementToNullTransition" => new ReconcilerStressFixtures.ElementToNullTransition(harness),
        "ReconcilerStress_ComponentUnmountCleanup" => new ReconcilerStressFixtures.ComponentUnmountCleanup(harness),
        "ReconcilerStress_NestedContainerUnmount" => new ReconcilerStressFixtures.NestedContainerUnmount(harness),
        "ReconcilerStress_KeyedLargeListStress" => new ReconcilerStressFixtures.KeyedLargeListStress(harness),
        "ReconcilerStress_MultiCycleReconcile" => new ReconcilerStressFixtures.MultiCycleReconcile(harness),
        "ReconcilerStress_KeyedPrefixTypeBreak" => new ReconcilerStressFixtures.KeyedPrefixTypeBreak(harness),
        // Control update tests
        "ControlUpdate_TextProperty" => new ControlUpdateFixtures.TextPropertyUpdate(harness),
        "ControlUpdate_ButtonProperty" => new ControlUpdateFixtures.ButtonPropertyUpdate(harness),
        "ControlUpdate_InputControls" => new ControlUpdateFixtures.InputControlsUpdate(harness),
        "ControlUpdate_DateTimePicker" => new ControlUpdateFixtures.DateTimePickerUpdate(harness),
        "ControlUpdate_Containers" => new ControlUpdateFixtures.ContainerUpdate(harness),
        "ControlUpdate_Collections" => new ControlUpdateFixtures.CollectionUpdate(harness),
        "ControlUpdate_Navigation" => new ControlUpdateFixtures.NavigationUpdate(harness),
        "ControlUpdate_Modifiers" => new ControlUpdateFixtures.ModifierUpdate(harness),
        "ControlUpdate_PaddingModifiers" => new ControlUpdateFixtures.PaddingModifierUpdate(harness),
        "ControlUpdate_Shapes" => new ControlUpdateFixtures.ShapeUpdate(harness),
        "ControlUpdate_StatusControls" => new ControlUpdateFixtures.StatusControlUpdate(harness),
        "ControlUpdate_Grid" => new ControlUpdateFixtures.GridUpdate(harness),
        "ControlUpdate_ModifiedElementUnwrap" => new ControlUpdateFixtures.ModifiedElementUnwrap(harness),
        "ControlUpdate_HyperlinkButton" => new ControlUpdateFixtures.HyperlinkButtonUpdate(harness),
        // Control update tests — wave 2
        "ControlUpdate2_NavigationView" => new ControlUpdateFixtures2.NavigationViewUpdate(harness),
        "ControlUpdate2_Image" => new ControlUpdateFixtures2.ImageUpdate(harness),
        "ControlUpdate2_AdditionalControls" => new ControlUpdateFixtures2.AdditionalControlsMountUpdate(harness),
        "ControlUpdate2_TextBitmaskDiff" => new ControlUpdateFixtures2.TextBitmaskDiffUpdate(harness),
        "ControlUpdate2_LegacyModifiedElement" => new ControlUpdateFixtures2.LegacyModifiedElementUpdate(harness),
        "ControlUpdate2_ButtonVariants" => new ControlUpdateFixtures2.ButtonVariantsUpdate(harness),
        "ControlUpdate2_ExpanderContent" => new ControlUpdateFixtures2.ExpanderContentUpdate(harness),
        "ControlUpdate2_VisibilityModifier" => new ControlUpdateFixtures2.VisibilityModifier(harness),
        "ControlUpdate2_RichEditBox" => new ControlUpdateFixtures2.RichEditBoxUpdate(harness),
        "ControlUpdate2_AutoSuggestBox" => new ControlUpdateFixtures2.AutoSuggestBoxUpdate(harness),
        // Modifier and event handler tests
        "ModifierEvent_EventHandlers" => new ModifierEventFixtures.EventHandlerModifiers(harness),
        "ModifierEvent_Brushes" => new ModifierEventFixtures.BrushModifiers(harness),
        "ModifierEvent_Tooltip" => new ModifierEventFixtures.TooltipModifier(harness),
        "ModifierEvent_Automation" => new ModifierEventFixtures.AutomationModifiers(harness),
        "ModifierEvent_ImplicitTransitions" => new ModifierEventFixtures.ImplicitTransitionModifier(harness),
        "ModifierEvent_BorderModifiers" => new ModifierEventFixtures.BorderModifiers(harness),
        "ModifierEvent_OnMountAction" => new ModifierEventFixtures.OnMountActionModifier(harness),
        // Rare control tests
        "RareControl_ColorPicker" => new RareControlFixtures.ColorPickerMountUpdate(harness),
        "RareControl_TeachingTip" => new RareControlFixtures.TeachingTipMount(harness),
        "RareControl_GridView" => new RareControlFixtures.GridViewMountUpdate(harness),
        "RareControl_PersonPicture" => new RareControlFixtures.PersonPictureUpdate(harness),
        "RareControl_RelativePanel" => new RareControlFixtures.RelativePanelMount(harness),
        "RareControl_CalendarView" => new RareControlFixtures.CalendarViewMountUpdate(harness),
        "RareControl_RichTextBlock" => new RareControlFixtures.RichTextBlockUpdate(harness),
        "RareControl_PasswordBox" => new RareControlFixtures.PasswordBoxUpdate(harness),
        "RareControl_ComboBoxRadioButtons" => new RareControlFixtures.ComboBoxRadioButtonsUpdate(harness),
        // Component hook tests
        "ComponentHook_UseReducerFunctional" => new ComponentHookFixtures.UseReducerFunctional(harness),
        "ComponentHook_UseReducerRedux" => new ComponentHookFixtures.UseReducerRedux(harness),
        "ComponentHook_UseMemoCallbackRef" => new ComponentHookFixtures.UseMemoCallbackRef(harness),
        "ComponentHook_UseEffectWithDeps" => new ComponentHookFixtures.UseEffectWithDeps(harness),
        "ComponentHook_TypedProps" => new ComponentHookFixtures.TypedPropsComponent(harness),
        "ComponentHook_UseWindowSize" => new ComponentHookFixtures.UseWindowSizeHook(harness),
        "ComponentHook_UseBreakpoint" => new ComponentHookFixtures.UseBreakpointHook(harness),
        "ComponentHook_MultipleComponents" => new ComponentHookFixtures.MultipleComponents(harness),
        // DSL and extension tests
        "DslExt_FluentModifierChain" => new DslExtensionFixtures.FluentModifierChain(harness),
        "DslExt_TransitionExtensions" => new DslExtensionFixtures.TransitionExtensions(harness),
        "DslExt_FactoryMethods" => new DslExtensionFixtures.DslFactoryMethods(harness),
        "DslExt_ShapeExtensions" => new DslExtensionFixtures.ShapeExtensions(harness),
        "DslExt_GridBuilders" => new DslExtensionFixtures.GridBuilders(harness),
        "DslExt_MenuDslMethods" => new DslExtensionFixtures.MenuDslMethods(harness),
        "DslExt_AttachedProperties" => new DslExtensionFixtures.AttachedProperties(harness),
        "DslExt_ErrorBoundaryElement" => new DslExtensionFixtures.ErrorBoundaryTest(harness),
        "DslExt_GroupElement" => new DslExtensionFixtures.GroupElementTest(harness),
        "DslExt_BrushAndFontModifiers" => new DslExtensionFixtures.BrushAndFontModifiers(harness),
        // FlexPanel CSS behavior — Section A (agreement)
        "CssStack_BasicVerticalNoSpacing" => new FlexPanelCssBehaviorFixtures.CssStack_BasicVerticalNoSpacing(harness),
        "CssStack_VerticalWithSpacing" => new FlexPanelCssBehaviorFixtures.CssStack_VerticalWithSpacing(harness),
        "CssStack_HorizontalWithSpacing" => new FlexPanelCssBehaviorFixtures.CssStack_HorizontalWithSpacing(harness),
        "CssStack_VerticalChildMarginsAndSpacing" => new FlexPanelCssBehaviorFixtures.CssStack_VerticalChildMarginsAndSpacing(harness),
        "CssStack_EmptyPanel" => new FlexPanelCssBehaviorFixtures.CssStack_EmptyPanel(harness),
        "CssStack_SingleChild" => new FlexPanelCssBehaviorFixtures.CssStack_SingleChild(harness),
        "CssStack_CollapsedChildExcluded" => new FlexPanelCssBehaviorFixtures.CssStack_CollapsedChildExcluded(harness),
        "CssStack_HorizontalCrossStretch" => new FlexPanelCssBehaviorFixtures.CssStack_HorizontalCrossStretch(harness),
        // FlexPanel CSS behavior — Section B (divergence)
        "CssDiverge_ExplicitHeightHonored" => new FlexPanelCssBehaviorFixtures.CssDiverge_ExplicitHeightHonored(harness),
        "CssDiverge_JustifyContentCenter" => new FlexPanelCssBehaviorFixtures.CssDiverge_JustifyContentCenter(harness),
        "CssDiverge_FlexGrowDistributesSpace" => new FlexPanelCssBehaviorFixtures.CssDiverge_FlexGrowDistributesSpace(harness),
        "CssDiverge_JustifyContentSpaceBetween" => new FlexPanelCssBehaviorFixtures.CssDiverge_JustifyContentSpaceBetween(harness),
        "CssDiverge_AlignSelfPerChild" => new FlexPanelCssBehaviorFixtures.CssDiverge_AlignSelfPerChild(harness),
        "CssDiverge_FlexWrap" => new FlexPanelCssBehaviorFixtures.CssDiverge_FlexWrap(harness),
        // Layout animation
        "LayoutAnimation_OffsetSetup" => new LayoutAnimationFixtures.OffsetAnimationSetup(harness),
        "LayoutAnimation_SpringSetup" => new LayoutAnimationFixtures.SpringAnimationSetup(harness),
        "LayoutAnimation_SizeSetup" => new LayoutAnimationFixtures.SizeAnimationSetup(harness),
        "ConnectedAnimation_MountUnmount" => new LayoutAnimationFixtures.ConnectedAnimationMountUnmount(harness),
        // Thread-safe hook stress tests
        "ThreadSafe_RapidBackgroundSetState" => new ThreadSafeHookFixtures.RapidBackgroundSetState(harness),
        "ThreadSafe_MultipleHooksConcurrent" => new ThreadSafeHookFixtures.MultipleHooksConcurrent(harness),
        "ThreadSafe_ReducerSerializationStress" => new ThreadSafeHookFixtures.ReducerSerializationStress(harness),
        "ThreadSafe_HighFrequencyLargeTree" => new ThreadSafeHookFixtures.HighFrequencyLargeTree(harness),
        "ThreadSafe_RenderCoalescing" => new ThreadSafeHookFixtures.RenderCoalescing(harness),
        // Animation system — Curve & Easing
        "Curve_RecordEquality" => new CurveTests.RecordEquality(harness),
        "Curve_PresetValues" => new CurveTests.PresetValues(harness),
        "Curve_FactoryMethods" => new CurveTests.FactoryMethods(harness),
        // Animation system — AnimationScope
        "AnimScope_SetRestore" => new AnimationScopeTests.ScopeSetRestore(harness),
        "AnimScope_NestingBehavior" => new AnimationScopeTests.NestingBehavior(harness),
        "AnimScope_NullCurveSuppresses" => new AnimationScopeTests.NullCurveSuppresses(harness),
        "AnimScope_WithAnimationIntegration" => new AnimationScopeTests.WithAnimationIntegration(harness),
        // Animation system — .Animate() modifier
        "Animate_ImplicitAnimationsCreated" => new AnimateModifierTests.ImplicitAnimationsCreated(harness),
        "Animate_TargetedProperties" => new AnimateModifierTests.TargetedProperties(harness),
        "Animate_MergesWithLayoutAnimation" => new AnimateModifierTests.MergesWithLayoutAnimation(harness),
        // Animation system — InteractionStates
        "InterState_StateMachineTransitions" => new InteractionStatesTests.StateMachineTransitions(harness),
        "InterState_PressedInheritsPointerOver" => new InteractionStatesTests.PressedInheritsFromPointerOver(harness),
        "InterState_ConfigImmutability" => new InteractionStatesTests.ConfigImmutability(harness),
        "InterState_NoLayoutProperties" => new InteractionStatesTests.NoLayoutProperties(harness),
        "InterState_MountIntegration" => new InteractionStatesTests.MountIntegration(harness),
        // Animation system — Transitions
        "Transition_TypeHierarchy" => new TransitionTests.TypeHierarchy(harness),
        "Transition_Asymmetric" => new TransitionTests.AsymmetricTransition(harness),
        "Transition_CurveResolutionPriority" => new TransitionTests.CurveResolutionPriority(harness),
        "Transition_MountUnmountIntegration" => new TransitionTests.MountUnmountIntegration(harness),
        // Animation system — WithAnimationAsync
        "AsyncAnim_TaskCompletes" => new AnimationAsyncTests.TaskCompletes(harness),
        "AsyncAnim_SequentialAwait" => new AnimationAsyncTests.SequentialAwait(harness),
        "AsyncAnim_ParallelWhenAll" => new AnimationAsyncTests.ParallelWhenAll(harness),
        // Animation system — Stagger
        "Stagger_DelayComputation" => new StaggerTests.DelayComputation(harness),
        "Stagger_ComposesWithLayoutAnimation" => new StaggerTests.ComposesWithLayoutAnimation(harness),
        "Stagger_ComposesWithEnterTransitions" => new StaggerTests.ComposesWithEnterTransitions(harness),
        // Animation system — Keyframe builder
        "Keyframe_BuilderProducesCorrectDef" => new KeyframeBuilderTests.BuilderProducesCorrectDef(harness),
        "Keyframe_TriggerValueChange" => new KeyframeBuilderTests.TriggerValueChange(harness),
        "Keyframe_LoopFlag" => new KeyframeBuilderTests.LoopFlag(harness),
        // Animation system — Scroll-linked
        "ScrollAnim_ParallaxExpression" => new ScrollAnimationTests.ParallaxExpression(harness),
        "ScrollAnim_FadeOutExpression" => new ScrollAnimationTests.FadeOutExpression(harness),
        "ScrollAnim_FadeInExpression" => new ScrollAnimationTests.FadeInExpression(harness),
        "ScrollAnim_ScaleRangeExpression" => new ScrollAnimationTests.ScaleRangeExpression(harness),
        "ScrollAnim_CustomExpression" => new ScrollAnimationTests.CustomExpression(harness),
        // Animation combination tests — single features
        "AnimCombo_SpringAlone" => new AnimationCombinationTests.AnimateSpringAlone(harness),
        "AnimCombo_EaseTargeted" => new AnimationCombinationTests.AnimateEaseTargeted(harness),
        "AnimCombo_LayoutAlone" => new AnimationCombinationTests.LayoutAnimAlone(harness),
        "AnimCombo_FadeEnter" => new AnimationCombinationTests.TransitionFadeEnter(harness),
        "AnimCombo_InteractionSetup" => new AnimationCombinationTests.InteractionStatesSetup(harness),
        "AnimCombo_KeyframesOnMount" => new AnimationCombinationTests.KeyframesOnMount(harness),
        "AnimCombo_StaggerOnContainer" => new AnimationCombinationTests.StaggerOnContainer(harness),
        // Animation combination tests — pairs
        "AnimCombo_AnimatePlusLayout" => new AnimationCombinationTests.AnimatePlusLayout(harness),
        "AnimCombo_AnimatePlusTransition" => new AnimationCombinationTests.AnimatePlusTransition(harness),
        "AnimCombo_AnimatePlusInteraction" => new AnimationCombinationTests.AnimatePlusInteraction(harness),
        "AnimCombo_LayoutPlusTransition" => new AnimationCombinationTests.LayoutPlusTransition(harness),
        "AnimCombo_TransitionCombined" => new AnimationCombinationTests.TransitionCombined(harness),
        "AnimCombo_AnimatePlusKeyframes" => new AnimationCombinationTests.AnimatePlusKeyframes(harness),
        "AnimCombo_InteractionPlusTransition" => new AnimationCombinationTests.InteractionPlusTransition(harness),
        // Animation combination tests — triple+
        "AnimCombo_Triple" => new AnimationCombinationTests.TripleCombination(harness),
        "AnimCombo_FullContainerCombo" => new AnimationCombinationTests.FullContainerCombo(harness),
        // Animation combination tests — update/rerender
        "AnimCombo_SurvivesUpdate" => new AnimationCombinationTests.AnimateSurvivesUpdate(harness),
        "AnimCombo_WithAnimationPlusAnimate" => new AnimationCombinationTests.WithAnimationPlusAnimate(harness),
        "AnimCombo_KeyframeTriggerUpdate" => new AnimationCombinationTests.KeyframeTriggerUpdate(harness),
        // Animation combination tests — removal
        "AnimCombo_AnimateRemoved" => new AnimationCombinationTests.AnimateRemoved(harness),
        // Core coverage tests
        "CoreCov_RichTextBlockParagraphUpdate" => new CoreCoverageFixtures.RichTextBlockParagraphUpdate(harness),
        "CoreCov_RichTextBlockInlineReconciliation" => new CoreCoverageFixtures.RichTextBlockInlineReconciliation(harness),
        "CoreCov_TemplatedGridViewMountUpdate" => new CoreCoverageFixtures.TemplatedGridViewMountUpdate(harness),
        "CoreCov_TemplatedFlipViewMountUpdate" => new CoreCoverageFixtures.TemplatedFlipViewMountUpdate(harness),
        "CoreCov_LazyVStackMountUpdate" => new CoreCoverageFixtures.LazyVStackMountUpdate(harness),
        "CoreCov_ContentDialogMount" => new CoreCoverageFixtures.ContentDialogMount(harness),
        "CoreCov_CommandBarMountUpdate" => new CoreCoverageFixtures.CommandBarMountUpdate(harness),
        "CoreCov_CommandHostMountUpdate" => new CoreCoverageFixtures.CommandHostMountUpdate(harness),
        "CoreCov_MenuBarMountUpdate" => new CoreCoverageFixtures.MenuBarMountUpdate(harness),
        "CoreCov_ThemeBindingApplication" => new CoreCoverageFixtures.ThemeBindingApplication(harness),
        "CoreCov_ResourceOverrideApplication" => new CoreCoverageFixtures.ResourceOverrideApplication(harness),
        "CoreCov_AccessibilityModifiers" => new CoreCoverageFixtures.AccessibilityModifierApplication(harness),
        "CoreCov_UseCommandHook" => new CoreCoverageFixtures.UseCommandHook(harness),
        "CoreCov_UseCommandTypedHook" => new CoreCoverageFixtures.UseCommandTypedHook(harness),
        "CoreCov_FlyoutMountUpdate" => new CoreCoverageFixtures.FlyoutMountUpdate(harness),
        "CoreCov_SemanticZoomMountUpdate" => new CoreCoverageFixtures.SemanticZoomMountUpdate(harness),
        "CoreCov_CompositorTransitions" => new CoreCoverageFixtures.CompositorTransitions(harness),
        "CoreCov_ThemeTransitions" => new CoreCoverageFixtures.ThemeTransitions(harness),
        "CoreCov_MemoComponentMountUpdate" => new CoreCoverageFixtures.MemoComponentMountUpdate(harness),
        "CoreCov_EventHandlerModifiers" => new CoreCoverageFixtures.EventHandlerModifiers(harness),
        "CoreCov_MenuFlyoutMount" => new CoreCoverageFixtures.MenuFlyoutMount(harness),
        "CoreCov_MediaPlayerMount" => new CoreCoverageFixtures.MediaPlayerMount(harness),
        "CoreCov_LazyHStackMount" => new CoreCoverageFixtures.LazyHStackMount(harness),
        "CoreCov_UseSyncCommandPassthrough" => new CoreCoverageFixtures.UseSyncCommandPassthrough(harness),
        "CoreCov_NavigationViewContentUpdate" => new CoreCoverageFixtures.NavigationViewContentUpdate(harness),
        "CoreCov_RelativePanelUpdate" => new CoreCoverageFixtures.RelativePanelUpdate(harness),
        "CoreCov_KeyframeCompositorAnimations" => new CoreCoverageFixtures.KeyframeCompositorAnimations(harness),
        "CoreCov_SwipeControlMount" => new CoreCoverageFixtures.SwipeControlMount(harness),
        "CoreCov_ListBoxMount" => new CoreCoverageFixtures.ListBoxMount(harness),
        "CoreCov_SelectorBarPipsPagerMount" => new CoreCoverageFixtures.SelectorBarPipsPagerMount(harness),
        "CoreCov_ThemeRefResolution" => new CoreCoverageFixtures.ThemeRefResolution(harness),
        "CoreCov_PopupRefreshContainerMount" => new CoreCoverageFixtures.PopupRefreshContainerMount(harness),
        "CoreCov_AnnotatedScrollBarMount" => new CoreCoverageFixtures.AnnotatedScrollBarMount(harness),
        "CoreCov_ContextProvideConsume" => new CoreCoverageFixtures.ContextProvideConsume(harness),
        "CoreCov_ChildCollectionExercise" => new CoreCoverageFixtures.ChildCollectionExercise(harness),
        "CoreCov_AttachedFlyoutModifier" => new CoreCoverageFixtures.AttachedFlyoutModifier(harness),
        "CoreCov_TreeViewUpdateExercise" => new CoreCoverageFixtures.TreeViewUpdateExercise(harness),
        "CoreCov_AdvancedModifierCoverage" => new CoreCoverageFixtures.AdvancedModifierCoverage(harness),
        "CoreCov_ColorSchemeHook" => new CoreCoverageFixtures.ColorSchemeHook(harness),
        "CoreCov_UseObservableDeep" => new CoreCoverageFixtures.UseObservableDeep(harness),
        "CoreCov_ErrorBoundaryUpdate" => new CoreCoverageFixtures.ErrorBoundaryUpdate(harness),
        "CoreCov_ExpanderChildUpdateDeep" => new CoreCoverageFixtures.ExpanderChildUpdateDeep(harness),
        "CoreCov_CanvasPositionUpdate" => new CoreCoverageFixtures.CanvasPositionUpdate(harness),
        // WinUI activation tests
        "WinUI_FontFamilyStringOnButton" => new WinUIActivationFixtures.FontFamilyStringOnButton(harness),
        "WinUI_FontFamilyInstanceOnBorder" => new WinUIActivationFixtures.FontFamilyInstanceOnBorder(harness),
        "WinUI_FontFamilyMergeOverwrites" => new WinUIActivationFixtures.FontFamilyMergeOverwrites(harness),
        "WinUI_TypographyModifiersMerge" => new WinUIActivationFixtures.TypographyModifiersMerge(harness),
        "WinUI_BorderFluentBrush" => new WinUIActivationFixtures.BorderFluentBrush(harness),
        "WinUI_ResourceBuilderStringBrush" => new WinUIActivationFixtures.ResourceBuilderStringBrush(harness),
        "WinUI_ResourceBuilderFluentChaining" => new WinUIActivationFixtures.ResourceBuilderFluentChaining(harness),
        "WinUI_ResourceExtensionSetsOverrides" => new WinUIActivationFixtures.ResourceExtensionSetsOverrides(harness),
        "WinUI_ResourceExtensionPreservesProps" => new WinUIActivationFixtures.ResourceExtensionPreservesProps(harness),
        "WinUI_ResourceExtensionMixedLiteralAndThemeRef" => new WinUIActivationFixtures.ResourceExtensionMixedLiteralAndThemeRef(harness),
        // Core coverage wave 2
        "CoreCov2_UsePersistedHook" => new CoreCoverageFixtures2.UsePersistedHook(harness),
        "CoreCov2_UseEffectCleanup" => new CoreCoverageFixtures2.UseEffectCleanup(harness),
        "CoreCov2_UseObservableTreeHook" => new CoreCoverageFixtures2.UseObservableTreeHook(harness),
        "CoreCov2_StandardCommandExercise" => new CoreCoverageFixtures2.StandardCommandExercise(harness),
        "CoreCov2_CommandInteropExercise" => new CoreCoverageFixtures2.CommandInteropExercise(harness),
        "CoreCov2_InfoBarActionButton" => new CoreCoverageFixtures2.InfoBarActionButton(harness),
        "CoreCov2_CalendarPipsPagerUpdate" => new CoreCoverageFixtures2.CalendarPipsPagerUpdate(harness),
        "CoreCov2_FrameAnimatedIconUpdate" => new CoreCoverageFixtures2.FrameAnimatedIconUpdate(harness),
        "CoreCov2_ParallaxViewMount" => new CoreCoverageFixtures2.ParallaxViewMount(harness),
        "CoreCov2_XamlHostMount" => new CoreCoverageFixtures2.XamlHostMount(harness),
        "CoreCov2_ComponentTypedProps" => new CoreCoverageFixtures2.ComponentTypedProps(harness),
        "CoreCov2_ColorSchemeHookExercise" => new CoreCoverageFixtures2.ColorSchemeHookExercise(harness),
        "CoreCov2_ContextScopeExercise" => new CoreCoverageFixtures2.ContextScopeExercise(harness),
        "CoreCov2_UseCommandAsyncExercise" => new CoreCoverageFixtures2.UseCommandAsyncExercise(harness),
        "CoreCov2_UseCommandTypedAsyncExercise" => new CoreCoverageFixtures2.UseCommandTypedAsyncExercise(harness),
        "CoreCov2_ProplessComponentShouldUpdate" => new CoreCoverageFixtures2.ProplessComponentShouldUpdate(harness),
        "CoreCov2_InfoBadgeMountUpdate" => new CoreCoverageFixtures2.InfoBadgeMountUpdate(harness),
        "CoreCov2_ListBoxUpdate" => new CoreCoverageFixtures2.ListBoxUpdate(harness),
        "CoreCov2_SelectorBarUpdate" => new CoreCoverageFixtures2.SelectorBarUpdate(harness),
        // Hosting coverage
        "Hosting_HostControlMountComponent" => new HostingCoverageFixtures.HostControlMountComponent(harness),
        "Hosting_HostControlMountFunc" => new HostingCoverageFixtures.HostControlMountFunc(harness),
        "Hosting_HostControlFactory" => new HostingCoverageFixtures.HostControlFactory(harness),
        "Hosting_HostControlRenderCallback" => new HostingCoverageFixtures.HostControlRenderCallback(harness),
        "Hosting_HostRenderStats" => new HostingCoverageFixtures.HostRenderStats(harness),
        "Hosting_HostDispose" => new HostingCoverageFixtures.HostDispose(harness),
        "Hosting_PageHelperExercise" => new HostingCoverageFixtures.PageHelperExercise(harness),
        "Hosting_XamlInteropRegister" => new HostingCoverageFixtures.XamlInteropRegister(harness),
        // Navigation coverage
        "NavCov_HandleAdvancedOps" => new NavigationCoverageFixtures.NavHandleAdvancedOps(harness),
        "NavCov_HandlePopTo" => new NavigationCoverageFixtures.NavHandlePopTo(harness),
        "NavCov_HandleSerialization" => new NavigationCoverageFixtures.NavHandleSerialization(harness),
        "NavCov_HandleNavigateOptions" => new NavigationCoverageFixtures.NavHandleNavigateOptions(harness),
        "NavCov_DeepLinkMap" => new NavigationCoverageFixtures.DeepLinkMapExercise(harness),
        "NavCov_TransitionFactories" => new NavigationCoverageFixtures.NavTransitionFactories(harness),
        "NavCov_HandleEvents" => new NavigationCoverageFixtures.NavHandleEvents(harness),
        "NavCov_DestinationGuard" => new NavigationCoverageFixtures.NavDestinationGuard(harness),
        "NavCov_DeepLinkQueryString" => new NavigationCoverageFixtures.NavDeepLinkQueryString(harness),
        "NavCov_DeepLinkOptionalParam" => new NavigationCoverageFixtures.NavDeepLinkOptionalParam(harness),
        "NavCov_DeepLinkWildcard" => new NavigationCoverageFixtures.NavDeepLinkWildcard(harness),
        "NavCov_DiagnosticsEvents" => new NavigationCoverageFixtures.NavDiagnosticsEvents(harness),
        "NavCov_SlideDistance" => new NavigationCoverageFixtures.NavSlideDistance(harness),
        // Validation coverage
        "ValCov_ValidationContext" => new ValidationCoverageFixtures.ValidationContextExercise(harness),
        "ValCov_BuiltInValidators" => new ValidationCoverageFixtures.BuiltInValidatorsExercise(harness),
        "ValCov_ValidateExtensions" => new ValidationCoverageFixtures.ValidateExtensionsExercise(harness),
        "ValCov_FormFieldRendering" => new ValidationCoverageFixtures.FormFieldRendering(harness),
        "ValCov_ValidationRule" => new ValidationCoverageFixtures.ValidationRuleExercise(harness),
        "ValCov_FormFieldHelpers" => new ValidationCoverageFixtures.FormFieldHelpersExercise(harness),
        // Controls coverage
        "ControlsCov_MaskEngineBasic" => new ControlsCoverageFixtures.MaskEngineBasic(harness),
        "ControlsCov_MaskEngineNavigation" => new ControlsCoverageFixtures.MaskEngineNavigation(harness),
        "ControlsCov_MaskEngineTokenTypes" => new ControlsCoverageFixtures.MaskEngineTokenTypes(harness),
        "ControlsCov_InputFormattersBasic" => new ControlsCoverageFixtures.InputFormattersBasic(harness),
        "ControlsCov_InputFormattersCasing" => new ControlsCoverageFixtures.InputFormattersCasing(harness),
        "ControlsCov_InputFormattersFiltering" => new ControlsCoverageFixtures.InputFormattersFiltering(harness),
        "ControlsCov_FormatterPipeline" => new ControlsCoverageFixtures.FormatterPipelineExercise(harness),
        "ControlsCov_AutoSuggestElement" => new ControlsCoverageFixtures.AutoSuggestElementCreation(harness),
        // Echo-suppression regression coverage
        "EchoSuppress_ColorPicker" => new EchoSuppressionFixtures.ColorPickerNoEcho(harness),
        "EchoSuppress_NumberBox" => new EchoSuppressionFixtures.NumberBoxNoEcho(harness),
        "EchoSuppress_NumberBoxMinMaxCoercion" => new EchoSuppressionFixtures.NumberBoxMinMaxCoercionNoEcho(harness),
        "EchoSuppress_ToggleSwitch" => new EchoSuppressionFixtures.ToggleSwitchNoEcho(harness),
        "EchoSuppress_CheckBox" => new EchoSuppressionFixtures.CheckBoxNoEcho(harness),
        "EchoSuppress_Slider" => new EchoSuppressionFixtures.SliderNoEcho(harness),
        "EchoSuppress_SliderMinMaxCoercion" => new EchoSuppressionFixtures.SliderMinMaxCoercionNoEcho(harness),
        "EchoSuppress_RatingControl" => new EchoSuppressionFixtures.RatingControlNoEcho(harness),
        "EchoSuppress_DatePicker" => new EchoSuppressionFixtures.DatePickerNoEcho(harness),
        "EchoSuppress_CalendarDatePicker" => new EchoSuppressionFixtures.CalendarDatePickerNoEcho(harness),
        "EchoSuppress_TimePicker" => new EchoSuppressionFixtures.TimePickerNoEcho(harness),
        "EchoSuppress_PasswordBox" => new EchoSuppressionFixtures.PasswordBoxNoEcho(harness),
        "EchoSuppress_TextField" => new EchoSuppressionFixtures.TextFieldNoEcho(harness),
        "EchoSuppress_ToggleSplitButton" => new EchoSuppressionFixtures.ToggleSplitButtonNoEcho(harness),
        // Control identity preservation
        "IdentityPreserve_ComboBox" => new IdentityPreservationFixtures.ComboBoxSurvivesSiblingUpdate(harness),
        "IdentityPreserve_ComboBoxElements" => new IdentityPreservationFixtures.ComboBoxElementItemsSurvivesSiblingUpdate(harness),
        "IdentityPreserve_RadioButtons" => new IdentityPreservationFixtures.RadioButtonsSurvivesSiblingUpdate(harness),
        "IdentityPreserve_TabView" => new IdentityPreservationFixtures.TabViewSurvivesSiblingUpdate(harness),
        "IdentityPreserve_Pivot" => new IdentityPreservationFixtures.PivotSurvivesSiblingUpdate(harness),
        "IdentityPreserve_ListBox" => new IdentityPreservationFixtures.ListBoxSurvivesSiblingUpdate(harness),
        "IdentityPreserve_SelectorBar" => new IdentityPreservationFixtures.SelectorBarSurvivesSiblingUpdate(harness),
        "IdentityPreserve_SplitView" => new IdentityPreservationFixtures.SplitViewSurvivesSiblingUpdate(harness),
        "ControlsCov_SearchManager" => new ControlsCoverageFixtures.SearchManagerExercise(harness),
        // Hooks coverage
        "HooksCov_FocusManagerRegistration" => new HooksCoverageFixtures.FocusManagerRegistration(harness),
        "HooksCov_FocusManagerNavigation" => new HooksCoverageFixtures.FocusManagerNavigation(harness),
        "HooksCov_FocusManagerWithControls" => new HooksCoverageFixtures.FocusManagerWithControls(harness),
        "HooksCov_UseFocusHookIntegration" => new HooksCoverageFixtures.UseFocusHookIntegration(harness),
        // DataGrid inline editing
        "DataGrid_EditLifecycle" => new DataGridEditFixtures.EditLifecycle(harness),
        "DataGrid_EditCommitCycle" => new DataGridEditFixtures.EditCommitCycle(harness),
        "DataGrid_EditCellColumnPlacement" => new DataGridEditFixtures.EditCellColumnPlacement(harness),
        "DataGrid_RapidSelection" => new DataGridEditFixtures.RapidSelection(harness),
        "DataGrid_ExternalStateUpdate" => new DataGridEditFixtures.ExternalStateUpdate(harness),
        "DataGrid_CellTypeFlipPreservesTrailingCells" => new DataGridEditFixtures.CellTypeFlipPreservesTrailingCells(harness),
        // DataGrid incremental paging
        "DataGrid_IncrementalLoadVerification" => new DataGridPagingFixtures.IncrementalLoadVerification(harness),
        "DataGrid_SmallDatasetFullyLoaded" => new DataGridPagingFixtures.SmallDatasetFullyLoaded(harness),
        // DataGrid scroll behavior and performance
        "DataGrid_ScrollPopulatesData" => new DataGridScrollFixtures.ScrollPopulatesData(harness),
        "DataGrid_ScrollBackPopulatesData" => new DataGridScrollFixtures.ScrollBackPopulatesData(harness),
        "DataGrid_ScrollPerfRelative" => new DataGridScrollFixtures.ScrollPerfRelative(harness),
        // DataGrid parity — hook-based paging path (Phase 3)
        "DataGrid_HookPagingMountAndLoad" => new DataGridParityFixtures.HookPagingMountAndLoad(harness),
        "DataGrid_HookPagingScrollPopulates" => new DataGridParityFixtures.HookPagingScrollPopulates(harness),
        "DataGrid_HookPagingScrollBack" => new DataGridParityFixtures.HookPagingScrollBack(harness),
        "DataGrid_HookPagingSmallDataset" => new DataGridParityFixtures.HookPagingSmallDataset(harness),
        "DataGrid_HookPagingEditLifecycle" => new DataGridParityFixtures.HookPagingEditLifecycle(harness),
        "AsyncResource.Framerate.DataGridScroll" => new DataGridParityFixtures.HookPagingFramerateScroll(harness),
        // UseResource integration fixtures
        "AsyncResource.BasicResolve" => new AsyncResourceFixtures.BasicResolve(harness),
        "AsyncResource.SyncCompleteNoFlash" => new AsyncResourceFixtures.SyncCompleteNoFlash(harness),
        "AsyncResource.StaleWhileRevalidate" => new AsyncResourceFixtures.StaleWhileRevalidate(harness),
        "AsyncResource.DepsChangeCancel" => new AsyncResourceFixtures.DepsChangeCancel(harness),
        "AsyncResource.UnmountDuringFetch" => new AsyncResourceFixtures.UnmountDuringFetch(harness),
        "AsyncResource.FocusRevalidate" => new AsyncResourceFixtures.FocusRevalidate(harness),
        // Pending bubble-up scope
        "AsyncResource.PendingBubbleUp" => new PendingFixtures.BubbleUp(harness),
        "AsyncResource.PendingWithOverride" => new PendingFixtures.WithOverride(harness),
        // UseMutation under real dispatcher
        "AsyncResource.MutationOptimistic" => new UseMutationFixtures.Optimistic(harness),
        "AsyncResource.MutationRollback" => new UseMutationFixtures.Rollback(harness),
        "AsyncResource.MutationInvalidates" => new UseMutationFixtures.Invalidates(harness),
        // UseInfiniteResource under real dispatcher
        "AsyncResource.InfiniteBasic" => new AsyncInfiniteResourceFixtures.InfiniteBasic(harness),
        "AsyncResource.InfinitePlaceholder" => new AsyncInfiniteResourceFixtures.InfinitePlaceholder(harness),
        "AsyncResource.InfiniteRefresh" => new AsyncInfiniteResourceFixtures.InfiniteRefresh(harness),
        "AsyncResource.InfiniteDepsChange" => new AsyncInfiniteResourceFixtures.InfiniteDepsChange(harness),
        // Framerate canaries (Phase 1)
        "AsyncResource.Framerate.DepsThrashing" => new AsyncResourceFramerateFixtures.DepsThrashing(harness),
        "AsyncResource.Framerate.RenderShortCircuit" => new AsyncResourceFramerateFixtures.RenderShortCircuit(harness),
        "AsyncResource.Framerate.CacheChurn" => new AsyncResourceFramerateFixtures.CacheChurn(harness),
        "AsyncResource.Framerate.FastRemount" => new AsyncResourceFramerateFixtures.FastRemount(harness),
        "AsyncResource.Framerate.DispatcherPressure" => new AsyncResourceFramerateFixtures.DispatcherPressure(harness),
        // Framerate canary (Phase 3 — UseMutation under DataGrid edit cadence)
        "AsyncResource.Framerate.DataGridEditMutation" => new AsyncResourceFramerateFixtures.DataGridEditMutation(harness),
        // Framerate canaries (Phase 2 — UseInfiniteResource)
        "AsyncResource.Framerate.ScrollFlood" => new AsyncInfiniteResourceFramerateFixtures.ScrollFlood(harness),
        "AsyncResource.Framerate.RapidEnsureRange" => new AsyncInfiniteResourceFramerateFixtures.RapidEnsureRange(harness),
        "AsyncResource.Framerate.RefreshMidScroll" => new AsyncInfiniteResourceFramerateFixtures.RefreshMidScroll(harness),
        "AsyncResource.Framerate.LruChurn" => new AsyncInfiniteResourceFramerateFixtures.LruChurn(harness),
        "AsyncResource.Framerate.ParallelPages" => new AsyncInfiniteResourceFramerateFixtures.ParallelPages(harness),
        // Pending scope framerate canary (Phase 4)
        "AsyncResource.Framerate.PendingChurn" => new PendingFixtures.FramerateChurn(harness),
        // AI agent devtools — MCP server exercised in-process
        "Devtools_VersionTool" => new DevtoolsFixtures.VersionTool(harness),
        "Devtools_ComponentsTool" => new DevtoolsFixtures.ComponentsTool(harness),
        "Devtools_WindowsTool" => new DevtoolsFixtures.WindowsTool(harness),
        "Devtools_TreeSummary" => new DevtoolsFixtures.TreeSummary(harness),
        "Devtools_TreeFullView" => new DevtoolsFixtures.TreeFullView(harness),
        "Devtools_TreeSelectorScope" => new DevtoolsFixtures.TreeSelectorScope(harness),
        "Devtools_ClickInvokesButton" => new DevtoolsFixtures.ClickInvokesButton(harness),
        "Devtools_TypeSetsTextBox" => new DevtoolsFixtures.TypeSetsTextBox(harness),
        "Devtools_FocusElement" => new DevtoolsFixtures.FocusElement(harness),
        "Devtools_WaitForTextChange" => new DevtoolsFixtures.WaitForTextChange(harness),
        "Devtools_WaitForTimeout" => new DevtoolsFixtures.WaitForTimeout(harness),
        "Devtools_ToggleFlipsCheckBox" => new DevtoolsFixtures.ToggleFlipsCheckBox(harness),
        "Devtools_InvokeDirectPattern" => new DevtoolsFixtures.InvokeDirectPattern(harness),
        "Devtools_StateReadsHooks" => new DevtoolsFixtures.StateReadsHooks(harness),
        "Devtools_ScreenshotReturnsPng" => new DevtoolsFixtures.ScreenshotReturnsPng(harness),
        "Devtools_SelectListItem" => new DevtoolsFixtures.SelectListItem(harness),
        "Devtools_ScrollByAndInto" => new DevtoolsFixtures.ScrollByAndInto(harness),
        "Devtools_LoggerWritesOneLinePerCall" => new DevtoolsFixtures.LoggerWritesOneLinePerCall(harness),
        "Devtools_UnknownSelectorStructuredError" => new DevtoolsFixtures.UnknownSelectorStructuredError(harness),
        "Devtools_NameSelectorMatchesButtonContent" => new DevtoolsFixtures.NameSelectorMatchesButtonContent(harness),
        "Devtools_TreeIdsUniqueAcrossSiblingsWithDifferentParents" => new DevtoolsFixtures.TreeIdsUniqueAcrossSiblingsWithDifferentParents(harness),
        "Devtools_FireRejectsLifecycleMethods" => new DevtoolsFixtures.FireRejectsLifecycleMethods(harness),
        "Devtools_FireInvokesNamedHandler" => new DevtoolsFixtures.FireInvokesNamedHandler(harness),
        "Devtools_WaitForTimeoutLoggedAsErr" => new DevtoolsFixtures.WaitForTimeoutLoggedAsErr(harness),
        "Devtools_InitializeHandshake" => new DevtoolsFixtures.InitializeHandshake(harness),
        "Devtools_SwitchComponentInvalidatesIds" => new DevtoolsFixtures.SwitchComponentInvalidatesIds(harness),
        // Coverage boost
        "CovBoost_ComponentHookWrappers" => new CoverageBoostFixtures.ComponentHookWrappers(harness),
        "CovBoost_ThemeTokenResolution" => new CoverageBoostFixtures.ThemeTokenResolution(harness),
        "CovBoost_ElementPoolExercise" => new CoverageBoostFixtures.ElementPoolExercise(harness),
        "CovBoost_FlexPanelAttachedProps" => new CoverageBoostFixtures.FlexPanelAttachedProps(harness),
        "CovBoost_FlexPanelContainerProps" => new CoverageBoostFixtures.FlexPanelContainerProps(harness),
        "CovBoost_UseSystemBackButton" => new CoverageBoostFixtures.UseSystemBackButtonExercise(harness),
        "CovBoost_UseHighContrastScheme" => new CoverageBoostFixtures.UseHighContrastSchemeExercise(harness),
        "CovBoost_UseAnnounce" => new CoverageBoostFixtures.UseAnnounceExercise(harness),
        "CovBoost_ElementPoolLifecycle" => new CoverageBoostFixtures.ElementPoolLifecycle(harness),
        "CovBoost_ThemeRefExplicitResolution" => new CoverageBoostFixtures.ThemeRefExplicitResolution(harness),
        "CovBoost_ComponentUseMutation" => new CoverageBoostFixtures.ComponentUseMutationExercise(harness),
        "CovBoost_ComponentUseResource" => new CoverageBoostFixtures.ComponentUseResourceExercise(harness),
        "CovBoost_FlexPanelUnloadCleanup" => new CoverageBoostFixtures.FlexPanelUnloadCleanup(harness),
        "CovBoost_ElementPoolDetach" => new CoverageBoostFixtures.ElementPoolDetach(harness),
        "CovBoost_UseWindowSizeBreakpoint" => new CoverageBoostFixtures.UseWindowSizeBreakpoint(harness),
        // Coverage boost wave 2
        "CovBoost2_SemanticElement" => new CoverageBoostFixtures2.SemanticElementExercise(harness),
        "CovBoost2_ValidationVisualizerStyles" => new CoverageBoostFixtures2.ValidationVisualizerStyles(harness),
        "CovBoost2_TitleBarMountUpdate" => new CoverageBoostFixtures2.TitleBarMountUpdate(harness),
        "CovBoost2_ReconcileChildPaths" => new CoverageBoostFixtures2.ReconcileChildPaths(harness),
        "CovBoost2_RichToolTipUpdate" => new CoverageBoostFixtures2.RichToolTipUpdate(harness),
        "CovBoost2_FlexChildPropChange" => new CoverageBoostFixtures2.FlexChildPropChange(harness),
        "CovBoost2_ResourceOverrideCleanup" => new CoverageBoostFixtures2.ResourceOverrideCleanup(harness),
        "CovBoost2_NavigationViewExercise" => new CoverageBoostFixtures2.NavigationViewExercise(harness),
        "CovBoost2_TemplatedListExercise" => new CoverageBoostFixtures2.TemplatedListExercise(harness),
        "CovBoost2_CompositionTransition" => new CoverageBoostFixtures2.CompositionTransitionExercise(harness),
        "CovBoost2_AnimationCurveExercise" => new CoverageBoostFixtures2.AnimationCurveExercise(harness),
        "CovBoost2_RichTextRebuild" => new CoverageBoostFixtures2.RichTextRebuild(harness),
        "CovBoost2_ElementPoolInteractiveReset" => new CoverageBoostFixtures2.ElementPoolInteractiveReset(harness),
        "CovBoost2_DataGridSearchSort" => new CoverageBoostFixtures2.DataGridSearchSort(harness),
        "CovBoost2_FocusTrapExercise" => new CoverageBoostFixtures2.SplitViewExercise(harness),

        // Input modifiers — spec 027 Tier 1
        "PointerMod_DoubleTappedAutoEnables" => new PointerModifierFixtures.DoubleTappedAutoEnables(harness),
        "PointerMod_RightTappedAutoEnables" => new PointerModifierFixtures.RightTappedAutoEnables(harness),
        "PointerMod_HoldingAutoEnables" => new PointerModifierFixtures.HoldingAutoEnables(harness),
        "PointerMod_ShapePointerHandlerAutoFillsTransparent" => new PointerModifierFixtures.ShapePointerHandlerAutoFillsTransparent(harness),
        "PointerMod_ShapeWithExplicitFillNotOverwritten" => new PointerModifierFixtures.ShapeWithExplicitFillNotOverwritten(harness),
        "PointerMod_GotLostFocusFires" => new PointerModifierFixtures.GotLostFocusFires(harness),
        "PointerMod_AutoEnableClearsOnDetach" => new PointerModifierFixtures.AutoEnableClearsOnDetach(harness),

        // Trampoline dispatch — spec 027 Tier 2
        "Trampoline_LatestHandlerWinsAfterRerender" => new TrampolineFixtures.LatestHandlerWinsAfterRerender(harness),
        "Trampoline_HandlerRemovedBecomesNoOp" => new TrampolineFixtures.HandlerRemovedBecomesNoOp(harness),
        "Trampoline_ReRenderSameControlUnderlyingRefStable" => new TrampolineFixtures.ReRenderSameControlUnderlyingRefStable(harness),

        // Gesture recognizers — spec 027 Tier 3
        "Gesture_OnPanSetsManipulationMode" => new GestureFixtures.OnPanSetsManipulationMode(harness),
        "Gesture_OnPanWithInertiaAddsInertiaFlag" => new GestureFixtures.OnPanWithInertiaAddsInertiaFlag(harness),
        "Gesture_OnPinchSetsScaleFlag" => new GestureFixtures.OnPinchSetsScaleFlag(harness),
        "Gesture_OnRotateSetsRotateFlag" => new GestureFixtures.OnRotateSetsRotateFlag(harness),
        "Gesture_PanAndPinchCombine" => new GestureFixtures.PanAndPinchCombine(harness),

        // LongPress + focus — spec 027 Tier 3 Part 2 / Tier 5 (Phase 4)
        "Gesture_OnLongPressAutoEnablesHolding" => new GestureFixtures.OnLongPressAutoEnablesHolding(harness),
        "Gesture_OnLongPressMouseEmulationOptIn" => new GestureFixtures.OnLongPressMouseEmulationOptIn(harness),
        "Focus_AccessKeySetsProperty" => new FocusFixtures.AccessKeySetsProperty(harness),
        "Focus_IsTabStopFalseSkipsTabNav" => new FocusFixtures.IsTabStopFalseSkipsTabNav(harness),
        "Focus_XYFocusKeyboardNavigationSets" => new FocusFixtures.XYFocusKeyboardNavigationSets(harness),
        "Focus_RefModifierPopulatesOnMount" => new FocusFixtures.RefModifierPopulatesOnMount(harness),
        "Focus_FocusManagerFocusReturnsTrueWhenMounted" => new FocusFixtures.FocusManagerFocusReturnsTrueWhenMounted(harness),

        // Commanding coverage — spec 027 Tier 4 (Phase 5)
        "Commanding_SplitButtonCommandInvokesExecute" => new CommandingCoverageFixtures.SplitButtonCommandInvokesExecute(harness),
        "Commanding_HyperlinkButtonCommandInvokesExecute" => new CommandingCoverageFixtures.HyperlinkButtonCommandInvokesExecute(harness),
        "Commanding_ToggleButtonCommandFiresOnToggle" => new CommandingCoverageFixtures.ToggleButtonCommandFiresOnToggle(harness),
        "Commanding_RepeatButtonCommandInvokesExecute" => new CommandingCoverageFixtures.RepeatButtonCommandInvokesExecute(harness),
        "Commanding_DisabledCommandDisablesControl" => new CommandingCoverageFixtures.DisabledCommandDisablesControl(harness),

        // Drag-and-drop — spec 027 Tier 6 (Phase 6a)
        "DragDrop_OnDragStartAutoSetsCanDrag" => new DragDropFixtures.OnDragStartAutoSetsCanDrag(harness),
        "DragDrop_OnDropAutoSetsAllowDrop" => new DragDropFixtures.OnDropAutoSetsAllowDrop(harness),
        "DragDrop_RawOnDropAutoSetsAllowDrop" => new DragDropFixtures.RawOnDropAutoSetsAllowDrop(harness),
        "DragDrop_DragEnterHandlerAutoSetsAllowDrop" => new DragDropFixtures.DragEnterHandlerAutoSetsAllowDrop(harness),
        "DragDrop_SourceAndTargetOnSameElement" => new DragDropFixtures.SourceAndTargetOnSameElement(harness),
        "DragDrop_DraggableWhenWithoutPayloadStillSetsCanDrag" => new DragDropFixtures.DraggableWhenWithoutPayloadStillSetsCanDrag(harness),

        // Devtools UX — spec 028 (DevtoolsMenu + UseDevtools + Observable<T>)
        "DevtoolsUx_MenuHiddenWhenDisabled" => new DevtoolsUxTests.MenuHiddenWhenDisabled(harness),
        "DevtoolsUx_MenuVisibleWhenEnabled" => new DevtoolsUxTests.MenuVisibleWhenEnabled(harness),
        "DevtoolsUx_ObservableToggleRerendersSubscribers" => new DevtoolsUxTests.ObservableToggleRerendersSubscribers(harness),

        // Selection-event wiring
        "SelectionEvt_ComboBox" => new SelectionEventFixtures.ComboBoxSelectionFires(harness),
        "SelectionEvt_RadioButtons" => new SelectionEventFixtures.RadioButtonsSelectionFires(harness),
        "SelectionEvt_ListView" => new SelectionEventFixtures.ListViewSelectionFires(harness),
        "SelectionEvt_GridView" => new SelectionEventFixtures.GridViewSelectionFires(harness),
        "SelectionEvt_FlipView" => new SelectionEventFixtures.FlipViewSelectionFires(harness),
        "SelectionEvt_TabView" => new SelectionEventFixtures.TabViewSelectionFires(harness),
        "SelectionEvt_Pivot" => new SelectionEventFixtures.PivotSelectionFires(harness),
        "SelectionEvt_NavigationView" => new SelectionEventFixtures.NavigationViewSelectionFires(harness),

        // Value-change / toggle event wiring
        "ValueEvt_CheckBox" => new ValueChangeEventFixtures.CheckBoxToggleFires(harness),
        "ValueEvt_RadioButton" => new ValueChangeEventFixtures.RadioButtonToggleFires(harness),
        "ValueEvt_ToggleSwitch" => new ValueChangeEventFixtures.ToggleSwitchToggleFires(harness),
        "ValueEvt_Slider" => new ValueChangeEventFixtures.SliderValueFires(harness),
        "ValueEvt_NumberBox" => new ValueChangeEventFixtures.NumberBoxValueFires(harness),
        "ValueEvt_RatingControl" => new ValueChangeEventFixtures.RatingControlValueFires(harness),
        "ValueEvt_PasswordBox" => new ValueChangeEventFixtures.PasswordBoxChangeFires(harness),
        "ValueEvt_ColorPicker" => new ValueChangeEventFixtures.ColorPickerChangeFires(harness),

        // Specialized editors — mount each editor standalone under real WinUI.
        "Editors_CheckBoxMounts" => new SpecializedEditorsTests.CheckBoxEditorMounts(harness),
        "Editors_ToggleMounts" => new SpecializedEditorsTests.ToggleEditorMounts(harness),
        "Editors_NumberMounts" => new SpecializedEditorsTests.NumberEditorMounts(harness),
        "Editors_DateMounts" => new SpecializedEditorsTests.DateEditorMounts(harness),
        "Editors_ColorMounts" => new SpecializedEditorsTests.ColorEditorMounts(harness),
        "Editors_ColorCompactMounts" => new SpecializedEditorsTests.ColorCompactEditorMounts(harness),
        "Renderers_HyperlinkMounts" => new SpecializedEditorsTests.HyperlinkRendererMounts(harness),
        "Renderers_ColorSwatchMounts" => new SpecializedEditorsTests.ColorSwatchRendererMounts(harness),

        // Reconcile-highlight overlay
        "ReconcileHighlight_MountCapturesElements" => new ReconcileHighlightTests.MountCapturesElements(harness),
        "ReconcileHighlight_UpdateCapturesModified" => new ReconcileHighlightTests.UpdateCapturesModified(harness),
        "ReconcileHighlight_NoCaptureWhenFlagOff" => new ReconcileHighlightTests.NoCaptureWhenFlagOff(harness),
        "ReconcileHighlight_ContainerNotModifiedWhenOnlyChildrenChange" => new ReconcileHighlightTests.ContainerNotModifiedWhenOnlyChildrenChange(harness),
        "ReconcileHighlight_UpdatePathNotRemount" => new ReconcileHighlightTests.UpdatePathNotRemount(harness),
        "ReconcileHighlight_MenuFlyoutUpdatesInPlace" => new ReconcileHighlightTests.MenuFlyoutUpdatesInPlace(harness),

        _ => null,
    };
}
